### ISSUE TITLE
Consider also including `import` in elpy-occur-definitions

### ISSUE THREAD

**Issue by xuhdev** [jorgenschaefer/elpy#1006]
Some symbols are legal in the current buffer because they are defined by being "imported"...

**Comment by jorgenschaefer** [comment]
Thanks for the suggestion! I don't think that including the (sometimes very long) list of import statements in the `C-c C-o` overview would be particularly helpful for what I use that command for, i.e. getting an overview of the code in the file. You seem to be using this differently?

**Comment by xuhdev** [comment]
I simply use it to see a list of symbols in the current buffer, as the name indicates... Perhaps, we can create 3 functions: `elpy-occur-imports`, `elpy-occur-functions`, `elpy-occur-classes` and make `elpy-occur-definitions` a combo that can be customized by users? It seems can also resolve a previous elpy issue for displaying only classes but I can't find that issue now...

**Comment by jorgenschaefer** [comment]
Hm. Do you also include assignments using `=`?

I'm not sure if the import case is really all that common a use case, especially considering imports are usually all lumped together and at the start of the file, but also because `M-x occur RET ^import RET`  is pretty fast to invoke (and easy to make a personal command if you use it often).

So I don't think that's a feature I'd like in Elpy. But thank you anyhow for bringing up the idea, it's always interesting to hear other usage types! :-)
