### ISSUE TITLE
Why is the preferred method of installation not MELPA?

### ISSUE THREAD

**Issue by sudarshang** [jorgenschaefer/elpy#1098]
The quick installation [documentation](https://github.com/jorgenschaefer/elpy/blob/master/README.rst#quick-installation) mentions adding a package archive. It will be easier for most users to install elpy via MELPA. If there are specific reasons to prefer installation via the elpy archive, could we have them in the README?

**Comment by jorgenschaefer** [comment]
Nah, the README is for important stuff, not for background info :-) 

The background can be found here: http://blog.jorgenschaefer.de/2014/03/elpy-moves-to-its-own-elpa.html

Most of it is not really too relevant anymore, and Elpy will move to MELPA Stable officially eventually. The only thing that annoys me is that I've had bugs in the past because other packages updated and broke things. But that's just how things are :-)

Does this answer your question?

**Comment by sudarshang** [comment]
Thanks! Closing this issue.
