### ISSUE TITLE
Error from Elpy backend jedi which 'import warnings' error

### ISSUE THREAD

**Issue by stardiviner** [jorgenschaefer/elpy#1134]
```
Output from Backend

There was some unexpected output from the Elpy backend. This is usually some
module that does not use correct logging, but might indicate a configuration
problem.

Output
'import warnings' failed; traceback:
'import warnings' failed; traceback:
```
This is the error output.

I tried `import warnings` in Python REPL, it works.
And tested with minimal Emacs init config, still has this issue.
Maybe somewhere in my jedi config is wrong? But I don't know where is the jedi config file.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! As the text indicates, this is not an error – the Python process is just emitting output. I do not know which library is emitting this output, it's just something that happens when Elpy is talking to Python. As Elpy does not know if this is relevant to you, it tells you about it. If it's not relevant to you, you can safely ignore it. I trust normal Elpy operation continues fine? I.e. completions and such keep working?

**Comment by stardiviner** [comment]
Yes, Elpy works fine. Just feel annonying everytime I start ELpy with this popup. Is there a way to debug into this?

**Comment by jorgenschaefer** [comment]
The window should not pop to the foreground again once it's opened once and you put in the background. If it does, that's a bug.

Debugging this is a bit tricky. Elpy (or rather, the libraries it uses, especially importmagic) will randomly import modules installed in your Python environment. Any of those modules could be responsible for emitting this on import. You could try and grep for `failed; traceback` in your `PYTHONPATH` I guess?

A possible and then simple solution would be to deinstall importmagic if you don't use it …

**Comment by stardiviner** [comment]
I see, thanks, I will take a try on the `PYTHONPATH`.

**Comment by ycz0926** [comment]
hello，i also meet the problem, the reproduce process like this:
1. open a pytho file with emacs
2. move the cursor or any input with keyboard, elpy will logout the waring info. if i do not move the cursor or do not input any word, the elpy will not logout the message
my emacs version is 25.3.2
my python verison is 3.6, the virtualenv is below:
```python
autoflake (1.1)
autopep8 (1.3.4)
elpy (1.18.0)
epc (0.0.5)
flake8 (3.5.0)
importmagic (0.1.7)
isort (4.3.0)
jedi (0.11.1)
mccabe (0.6.1)
parso (0.1.1)
pip (9.0.1)
pkg-resources (0.0.0)
pycodestyle (2.3.1)
pyflakes (1.6.0)
rope (0.10.7)
setuptools (38.4.0)
sexpdata (0.0.3)
wheel (0.30.0)
yapf (0.20.1)
```
the screenshot:
![_009](https://user-images.githubusercontent.com/18224691/35667853-18706016-076a-11e8-9560-972e17b48c07.jpg)

**Comment by ycz0926** [comment]
if it's not a bug, how i can stop elpy logging this message...? 
thanks

**Comment by galaunay** [comment]
A workaround would be to overwrite the elpy function poping-up those messages.
You can do so by adding those lines in your init file after loading elpy:
```Elisp
(defun elpy-rpc--handle-unexpected-line (line)
  "Handle an unexpected line from the backend.

This is usually an error or backtrace."
  (message "[Elpy backend output] %s" line)) 
```
It will display a message instead of poping up a window.
If it is still annoying, you can remove everything with something like that:
```Elisp
(defun elpy-rpc--handle-unexpected-line (line)
  "Handle an unexpected line from the backend.

This is usually an error or backtrace."
  nil)
```

Anyway, Importmagic support was dropped, so if this is related to importmagic importing stuff, this issue should be fixed by the next elpy version.

**Comment by ycz0926** [comment]
@galaunay thanks for your reply, the solution may solve my probleam at this elpy's version, anyway i am glad to hear that, the next elpy version will fix the issue ...

**Comment by galaunay** [comment]
Don't hesitate to reopen this issue if it is not the case.

**Comment by ycz0926** [comment]
ok
