### ISSUE TITLE
run IPython inside of term/ansi-term

### ISSUE THREAD

**Issue by HuStmpHrrr** [jorgenschaefer/elpy#1159]
I am recently switching to Emacs from Vim and trying to get familiar with the editor via python. It's new to me that the editor can interact with a interpreter session from within. However, the interpreter works on comint mode which misses many features IPython would have offered in a raw tty. After checking around, I noticed that Emacs also has terminal emulator built in. Is there any specific reason why we would prefer comint mode instead of a full featured terminal working 99% of the time(except some corner cases which doesn't really matter that much)?

Pardon me if it's a stupid question to ask but my research indicates that term just beats comint to the ground.

**Comment by jorgenschaefer** [comment]
> Is there any specific reason why we would prefer comint mode

Yes. Primarily because comint mode makes it easy to interact with the subprocess from within Emacs, while terminal sessions have no concept of "last input" and the like. If someone adds good support for interacting with the subprocess to the terminal emulation packages, we could use those, too.

This is the reason why pretty much all program modes talk to their subprocesses via comint mode.

Does this answer the question? :-)

**Comment by HuStmpHrrr** [comment]
nice. thanks a lot.

**Comment by jorgenschaefer** [comment]
You're welcome, and enjoy Elpy (even without IPython in a terminal emulator) :-)
