### ISSUE TITLE
Elpy starts Python processes at the root of my git tree, not the module's directory

### ISSUE THREAD

**Issue by jerlev** [jorgenschaefer/elpy#1249]
(I'm submitting this after posting a question on emacs.stackexchange.com and not getting any answer or comment - https://emacs.stackexchange.com/q/37570/10184)

I'm using Emacs 25.3.1, Elpy v20171212.850, and Python 3.6.3 on MacOS 10.13.2 .

I have a project tracked with Git in `~/MyProject`, with the usual git data in `~/MyProject/.git` and `~/MyProject/.gitignore`. I have some Python modules in `~/MyProject/Python`. If, for example, I open one of these modules and, from that buffer, call `elpy-shell-switch-to-shell`, or `elpy-shell-send-region-or-buffer`, then Elpy starts a new Python process in `~/MyProject` instead of `~/MyProject/Python`. This odd behaviour has only started occurring recently (might be since the last Elpy upgrade, but not sure - I upgrade fairly frequently).

Interestingly, if I delete the Git metadata *and* kill/reopen the Python module (simply killing the Python REPL buffer is insufficient), then the Python process starts as expected in `~/MyProject/Python`.

Any idea how I can debug this?

**Comment by rgemulla** [comment]
Yes, the default behavior has changed recently; see [the documentation](https://elpy.readthedocs.io/en/latest/ide.html#the-shell-buffer).

You can set ```elpy-shell-use-project-root``` to ```nil``` to start the shell in the directory of the Python file as before. Alternatively, modify your ```MyProject/Python``` directory so that it is detected as a project root; see ```elpy-project-root-finder-functions```.

Does this help?

**Comment by jerlev** [comment]
Thanks for pointing this out, and sorry for bringing up an "issue" that happens to be a feature! There have been many changes in Elpy recently; I will reread the documentation.

**Comment by rgemulla** [comment]
Alright! Please reopen in case there is still an issue.

**Comment by fmitha** [comment]
This isn't working for me with elpy 1.34. I currently have

    (setq elpy-shell-use-project-root nil)         

in my `~/.emacs`. This used to work, but no longer does.

I checked, and the following text appears in customize:

> elpy-shell-use-project-root is a variable defined in ‘elpy-shell.el’.
> Its value is nil
> Original value was t
> 
>   This variable is obsolete since 1.32.0;
>   use ‘elpy-shell-starting-directory’ instead.

But elpy-shell-use-project-root still appears in customize. If it's obsolete (and apparently not working, in any case), it should just be removed. And why was this changed? It's preferable when things don't break, because one has to track down and fix the breakage. And life is just too short.

Anyway, I set ‘elpy-shell-starting-directory’ via customize, and the correct syntax, per customize, is

    (elpy-shell-starting-directory (quote current-directory))

which works.
