### ISSUE TITLE
[Question] - parallel documentation a la 'Scientific Mode'

### ISSUE THREAD

**Issue by Nicholas-Mitchell** [jorgenschaefer/elpy#1276]
This is first of all a question, then perhaps later a feature request.

I can look up any documentation (docstrings) that Elpy can find using the simple `elpy-doc`  with the cursor over the object of interest.

I have recently tried out the PyCharm take on things and have discovered the Scientific Mode, whereby the corresponding documentation for wherever the cursor is, is automatically shown in a separate 'buffer'. Here is the examples on [their relevant release video](https://youtu.be/OHwh0c8UsW4?t=1m15s). While I can hit `C-c C-d` as often as I like, I really like the way PyCharm gives the documentation according to the current state of auto-complete.

For example, if I am at `numpy.random.` - the documentation is shown for wherever my cursor then resides on the list of possible completions. this allows me to much more quickly decide which completion I need - it does not interrupt my flow of thinking.
(The other features shown in that Data Science section of the video would be nice to have, like plotting outputs directly in the same buffer etc, but Emacs itself has some limitations there, I know).

Given how quickly the `elpy-doc` call works, I can't imagine it would be impractical to have it running, say every 0.5 seconds.

I get the feeling this might be simple to implement, but I am sadly not as proficient in E-lisp as required to build this myself.

Does anybody have thoughts on this? Would anybody else want this?

**Comment by galaunay** [comment]
For displaying documentation based on what is under the cursor,  
I guess the way `company-idle-delay` works is a good example of how to do it (notably the `company-post-command` function, that use `run-with-timer`, if you want to take a look and learn a bit of elisp :) ).

Though, on some of my (old) computers, `elpy-doc` can sometimes be quite slow (several seconds) to extract the documentation from my packages. 
So running elpy-doc as an asynchronous process (like pycharm does it) seems necessary to avoid having Emacs freeze each second to get the documentation.
It does make implementing this more difficult.

Anyway, it is an interesting feature, I will give it a try (unless you want to), see how it goes.

Regarding having documentation during completion, you should take a look at [company-quickhelp](https://github.com/expez/company-quickhelp), it does exactly that, but in a popup instead of in an adjacent window.

**Comment by Nicholas-Mitchell** [comment]
@galaunay - thanks for implementing it!

Could you please tell me the best way to try it out? Just copy the relevant code from `elpy.el` or will it be necessary to clone the whole repo? If so, how do I do that without touching my current setup at all? Thanks in advance  :smile:

**Comment by galaunay** [comment]
Sure, 

If your elpy installation is up-to-date, the simplest way is to download the new version of `elpy.el`, open it in emacs and then call `(eval-buffer)`.
After that, open a python buffer and it should be on.
To reset the change, just restart emacs.

If it doesn't work, you will have to overwrite all the elpy files with their new versions.
You will be able to get your old install back by reinstalling elpy.

Delay for updating doc is 0.5s, though you can adjust it through the `elpy-autodoc-delay` option. 
You can set this to zero, it should not freeze emacs, but it will have an non-neglectible impact on your cpu, as it will search for doc each time you move your cursor...

I am working on the PR now, any feedback would be welcome :).

**Comment by Nicholas-Mitchell** [comment]
Afraid the quick way of testing isn't working - I will give it a go with the full installation once I have some time and get back to you!  Thanks again for the implementation!

**Comment by galaunay** [comment]
I made a PR (#1288) for this, 
See you there if you have any feedback on this !
