### ISSUE TITLE
Give some way to access python.el completions

### ISSUE THREAD

**Issue by memeplex** [jorgenschaefer/elpy#1399]
python.el provides completions related to the current python comint interaction. These completions could be even more useful than jedi ones for "scratch" buffers connected to an interactive session. But elpy:

1. Disables the company capf backend.
2. Captures standard keybindings for completion-at-point.

There is a comment in the code that removes the capf backend:

```
     ;; Add our own backend and remove a bunch of backends that
     ;; interfere in Python mode.
```

Could an option be added to keep capf here?

**Comment by memeplex** [comment]
For now I'm doing

```elisp
(add-hook 'elpy-mode-hook
	  (lambda ()
	    (setcdr company-backends
		    (cons #'company-capf (cdr company-backends)))))
```

but it's not very convenient.

**Comment by galaunay** [comment]
I don't know why the capf backend was removed in the first place.
I think the good way of doing it would be to fall back to capf when elpy fail.

Is the following backends list giving you what you want ?
```Elisp
 (set (make-local-variable 'company-backends)
      (cons 'elpy-company-backend
            (cons 'company-capf
                  (delq 'company-semantic
                        (delq 'company-ropemacs
                               (mapcar #'identity company-backends)))))))

```

**Comment by memeplex** [comment]
I think it should but maybe it's better to let python.el position its own completion function in the list, it should known better where it belongs.

**Comment by galaunay** [comment]
Even if we don't remove capf backend, it will never be called, as elpy's backend will be called first.

python.el offers a backend based on what is loaded in the interpreter and Elpy offers a backend using jedi. You cannot use both.

In fact, it is not completing true as you can combine the two backends with something like that:
```Elisp 
     (setq company-backends (list (list 'elpy-company-backend 'company-capf))
``` 

but this creates a lot of duplicates.

**Comment by memeplex** [comment]
I might be wrong here  but my understanding is that company returns the
first completion it receives from the list of backends, so I assumed that
if jedi had nothing to say then the running repl could have a chance to
return some completion. But it might be better to bind another key to a
function that just override the list of backends and put python.el first
just for the time.

**Comment by galaunay** [comment]
This is what I expected as well, but looking at `company-backends` documentation, it seems that company uses the first backend that 'think' it can complete:
> Each backend is a function that takes a variable number of arguments.
The first argument is the command requested from the backend.  It is one
of the following:
> ‘prefix’: The backend should return the text to be completed.  It must be
text immediately before point.  **Returning nil from this command passes
control to the next backend.**  The function should return ‘stop’ if it
should complete but cannot (e.g. when in the middle of a symbol).
Instead of a string, the backend may return a cons (PREFIX . LENGTH)
where LENGTH is a number used in place of PREFIX’s length when
comparing against ‘company-minimum-prefix-length’.  LENGTH can also
be just t, and in the latter case the test automatically succeeds.
> [...]

It kind of makes sens, as jedi completions are retrieved asynchronously, there is no way to know if elpy backend will be successful a priori.

But it seems possible to merge the list of candidates from both backends (I raised a feature request #1402). It may be a good improvement for elpy completion.

In the meantime, If you just want to use python.el completion, you don't even have to mess with the backend list, you can just bind `company-capf`:
```Elisp
(define-key elpy-mode-map (kbd "C-c C-i") 'company-capf)
```

Would you have a proposition for the keybinding to use (I have most of the elpy function remaped so I am not very familiar with the default keybindings anymore) ?

**Comment by memeplex** [comment]
Can we close this since https://github.com/jorgenschaefer/elpy/pull/1403 was merged or is there anything else missing yet?

**Comment by memeplex** [comment]
> Would you have a proposition for the keybinding to use

I think alt-tab is the most natural option. Some shell modes also make the distinction between pcomplete (simply tab) or completion at point (alt-tab) for different completion modes. Maybe elpy could set this by default, even if company now includes the capf backend candidates.

**Comment by galaunay** [comment]
Merging the two backends has lead to some problems, so it is deactivated by default ATM.
You will need to set `elpy-company-add-completion-from-shell` to `t` to activate it.

It *should* works fine following the last PRs.

I am closing this, please re-open if there is any issues.

**Comment by memeplex** [comment]
@galaunay I saw your comment in the PR regarding not adding anything to the doc since completion mechanism is mostly undocumented anyway. I'm ok with that as far as you set `elpy-company-add-completion-from-shell` to `t` by default. If you find that default unreasonable, then please do add a line to the user guide, since the only way to get aware of this capability now is to, probably fortuitously, read this thread up to the comment above or discover the customization variable.

**Comment by galaunay** [comment]
The feature was aimed to be activated by default.
But it is not working very well at the moment, making Emacs hangs (see #1482).

If I can make it works properly, it will be activated by default (and i'll update the documentation).
If not, we will have to remove the feature anyway.
