### ISSUE TITLE
Support different backends from elpy-test

### ISSUE THREAD

**Issue by jorgenschaefer** [jorgenschaefer/elpy#140]
elpy-test should support different backends. The main function should just call a configurable function with file name, class name, and method name, which then can do whatever else it wants to do.

The default configuration would provide nosetests and unittest support.

Then there is the option of running tests in `compilation-start` or in `pdb` …
## Nosetests

nose.el currently runs this with `[-v] [--pdb] -w <dir> -c <dir>setup.cfg <testnames>`.
## unittest

unittest discover does not handle classes and methods, sadly, so we can only call `python -m unittest discover -s <startdir> -p "test*.py" -t <topleveldir>`

The start directory can be a package name, but that does not seem to work well (it searches the parent directory).

**Comment by Apteryks** [comment]
Hello Jorgen, and thanks for the great software! :)

Is there a simple way to have an pre-defined test-runner, say "py.test", use `pdb' rather than `console' so that when using the --pdb argument we can fall into the debugger and interact with the process?

I could define a brand new test-runner called "py.test-pdb" which would in turn implement its own internal `elpy-test-run',  but that seems a bit overkill given that I only want to add an argument to "py.test".

Right now I'm overriding `elpy-test-run' globally in my ~/.emacs like this:
````
(with-eval-after-load 'elpy
  ;; Override elpy-test-run so that we can debug interactively with
  ;; pdb when "--pdb" arg was passed as a test argument or
  ;; pdb.set_trace is used.
  (defun elpy-test-run (working-directory command &rest args)
	"Run COMMAND with ARGS in WORKING-DIRECTORY as a test
	command. If \"--pdb\" is found in the ARGS, we start the process with `pdb';
        otherwise use a `compile'."
	(let ((default-directory working-directory)
		  (cmd (mapconcat #'shell-quote-argument (cons command args) " ")))
	  (if (member "--pdb" args)
		  (pdb cmd)
		(compile cmd)))))
````

This work well and is rather brief but also a hack. Would you have a recommendation for a better way to achieve this?

**Comment by jorgenschaefer** [comment]
Hm. It might be an idea to have a customize option that defaults to `compile` – would that work for you?

**Comment by Apteryks** [comment]
Unless you know of a way to make `pdb` gain the "file names as link" goodness that `compile` provides, I wouldn't want to use `pdb` when I do not intend to debug. So it would be helpful but not 100% satisfying.

What might be more flexible would be to allow an optional extra argument to `elpy-test-run` such as &optional buffer-mode. This would allow people to define in their test runners extra logic to dynamically choose the buffer-mode they'd like to use. We could even upgrade our current `elpy-test-pytest-runner` function (I saw that nosetest also has a --pdb option) to do that out-of-the-box; one could argue that hanging in `compile` instead of allowing interactive debugging when the py.test command is given the '--pdb' flag is a bug :)

Does that sound reasonable? If yes I wouldn't mind providing a patch as a first draft.

**Comment by jorgenschaefer** [comment]
You can let-bind such a global variable before calling elpy-test in your own functions … a bit unorthodox in other languages, but pretty standard in Emacs Lisp. :-) Wouldn't that work?

Whoever passes `--pdb` to the command is responsible for also setting the other options to make this work, it's not Elpy's job to guess what a command needs like this, I think. If a user configures `elpy-test-pytest-runner-command`, they can also configure that option. If a command calls `elpy-test-run` with that argument, they can let-bind the option, too.

**Comment by Apteryks** [comment]
Hello Jorgen! Thanks for taking the time to write back.

> You can let-bind such a global variable before calling elpy-test in your own functions … a bit unorthodox in other languages, but pretty standard in Emacs Lisp. :-) Wouldn't that work?
> 

After some thoughts, that would work, yes! I could then create some `elpy-test-pytest-runner-debug`, and bind this to say, C-c T. This test runner would simply add the '--pdb' option to  `elpy-test-pytest-runner-command` and let-bind the new customizable buffer type, and then simply defer to the usual `elpy-test-pytest-runner` function.

**Comment by jorgenschaefer** [comment]
I pushed a change for this to master, as 2cf34af – can you check if that works for you?

**Comment by azzamsa** [comment]
Any documentation on 'how to use elpy with nosetests' ?

Thanks

**Comment by azzamsa** [comment]
> Does M-x customize-variable RET elpy-test-runner help?

Oh. Thanks.

After some research. I prefer to use Eshell to run `nosetests` with the help of `virtualenvwrapper.el`. But sometimes when I don't need shell. I just use pyenv to activatave venv.

Thanks for your contribution to community,
