### ISSUE TITLE
Still have to disable flymake module

### ISSUE THREAD

**Issue by memeplex** [jorgenschaefer/elpy#1400]
I still need to disable flymake module in order to get flymake running as expected.

The duplicated error messages problem has been fixed.

Now the issues when enabling the module are:

1. No feedback in the modeline
2. Only check when file is saved

After disabling the module I get:

1. Instant feedback
2. The usual warning/error counts in the modeline

Maybe the module is intended to be removed since python.el is already taking care of flymake, but at this point an out-of-the-box install of elpy is still not functional in emacs 26 regarding flymake.

**Comment by galaunay** [comment]
Regarding the instant feedback, this is quite intended. It is meant to be a decent default configuration for python, and the reasons invoked in the code are the followings:
> -  `flymake-no-changes-timeout` is set to 60: The original value of 0.5 is too short for Python code, as that will result in the current line to be highlighted most of the time, and that's annoying. This value might be on the long side, but at least it does not, in general, interfere with normal interaction.
> - `flymake-start-syntax-check-on-newline` is set to `nil`: This should be nil for Python, as most lines with a colon at the end will mean the next line is always highlighted as error, which is not helpful and mostly annoying.

Regarding the warning/error counts in the modeline, this is also intended, as Elpy removes flymake from the modeline (to avoid clutter in the modeline and because flymake didn't have such nice modeline indicator before ?).

So nothing unexpected here.
However, if you have propositions on how to improve Elpy default configuration, they are always welcome.

**Comment by memeplex** [comment]
If that's the expected behavior I'm ok with that. I just became used to the
python.el behavior and assumed something was wrong. Sorry.

**Comment by galaunay** [comment]
No problem.
I guess I can close this then.

**Comment by memeplex** [comment]
Sure. Btw, I find the current indicators in the modeline quite useful and
good looking, I don't know how they were before.
