### ISSUE TITLE
Not showing doc for classmethods

### ISSUE THREAD

**Issue by PeterSterner** [jorgenschaefer/elpy#1423]
I often use C-c C-d to call elpy-doc. When I call a function defined somewhere then in the minibuffer elpy shows me the parameters of the function I'm calling.

My problem is it does not work when the function is a classmethod (decorated with "@classmethod").

Thanks in advance and thanks to all of you for a great emacs package!

Best regards
Petey

# My configuration

## Result of `(elpy-config)`
Elpy Configuration

Virtualenv........: None
RPC Python........: 3.6.6 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 26.1
Elpy..............: 1.23.0
Jedi..............: 0.12.1
Rope..............: 0.9.4-1
Autopep8..........: 1.3.5
Yapf..............: 0.22.0
Black.............: 18.6b4
Syntax checker....: flake8 (/home/petey/.local/bin/flake8)

**Comment by galaunay** [comment]
Thanks for the report.

I tried with the following minimal example (for python3.6, emacs26.1, elpy1.23.0 and jedi0.12.1):
```Python
class Entity(object):
    def __init__(self, a, b, c):
        """

        """
        self.a = a
        self.b = b
        self.c = c

    @classmethod
    def class_meth(cls, arg1):
        return cls(arg1, arg1, arg1)

ent = Entity(1, 2, 3)
ent.class_meth(
```
and I got `class_meth(param arg1)` in the minibuffer, as expected.

Could you try with this example, and see if it works ?

**Comment by galaunay** [comment]
My bad.
You are right, it does not work.
(It works if you try first without the `@classmethod`, then with it, which confused me).

It seems to be a problem with jedi, that return the calltip for the functions `_method` of the decorator, rather than for the calltip for the defined function.

Unfortunately, I don't think we can do anything from Elpy's side.
I would recommend reporting this upstream to [jedi](https://github.com/davidhalter/jedi).

**Comment by petey33** [comment]
@galaunay Thanks a lot for your time and helping me out. I have reported it to jedi.

**Comment by galaunay** [comment]
Thanks,
I am just pasting the [issue](https://github.com/davidhalter/jedi/issues/498) link here in case of future related issues.
