### ISSUE TITLE
IPython Shell magic function %hist outputs lots of junk history 

### ISSUE THREAD

**Issue by shelper** [jorgenschaefer/elpy#1430]
# Summary

I am using spacemacs with Emacs V26.1, with package elpy, on a Macbook. I believe this also happens on Windows. the issue is when I run the magic function %hist in the IPython shell, i got lots of information like below:

```
import codecs, os;__pyfile = codecs.open('''/var/folders/y1/197_jjzs1yv2qz0m26z1jkxw0000gn/T/pysfAkcq''', encoding='''utf-8''');__code = __pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''/var/folders/y1/197_jjzs1yv2qz0m26z1jkxw0000gn/T/pysfAkcq''');exec(compile(__code, '''/var/folders/y1/197_jjzs1yv2qz0m26z1jkxw0000gn/T/pysfAkcq''', 'exec'));
import codecs, os;__pyfile = codecs.open('''/var/folders/y1/197_jjzs1yv2qz0m26z1jkxw0000gn/T/pythwlpb''', encoding='''utf-8''');__code = __pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''/var/folders/y1/197_jjzs1yv2qz0m26z1jkxw0000gn/T/pythwlpb''');exec(compile(__code, '''/var/folders/y1/197_jjzs1yv2qz0m26z1jkxw0000gn/T/pythwlpb''', 'exec'));
import codecs, os;__pyfile = codecs.open('''/var/folders/y1/197_jjzs1yv2qz0m26z1jkxw0000gn/T/pyUwYsfX''', encoding='''utf-8''');__code = __pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''/var/folders/y1/197_jjzs1yv2qz0m26z1jkxw0000gn/T/pyUwYsfX''');exec(compile(__code, '''/var/folders/y1/197_jjzs1yv2qz0m26z1jkxw0000gn/T/pyUwYsfX''', 'exec'));
```
anyone had the same issue and is there a way to remove these?

# Steps to reproduce
run `run-python`, then run couple of command, e.g., `print('helloworld') and run `%hist`

# My configuration
## OS
mac os 10.13

## Result of `(elpy-config)`
```
Virtualenv........: None
RPC Python........: 3.5.2 (/Users/zyuan/anaconda/bin/python)
Interactive Python: ipython (/Users/zyuan/anaconda/bin/ipython)
Emacs.............: 26.1
Elpy..............: 1.23.0
Jedi..............: 0.12.1
Rope..............: 0.9.4-1
Autopep8..........: Not found (1.3.5 available)
Yapf..............: Not found (0.22.0 available)
Black.............: Not found (18.6b4 available)
Syntax checker....: Not found (flake8)

```

## Elpy configuration in my init.el
Vanilla

**Comment by galaunay** [comment]
`python.el` does not actually send string to the shell, but files containing the code.
The lines you are seing are just that: `python.el` sending your code to the shell.

It would indeed be nice not to record those lines in the python history, but this is something that has to be done in `python.el` (if doable...).
I guess you will have to report upstream for that :).

**Comment by Salompas** [comment]
I am also getting this noise when sending code to the interpreter with `C-c C-c`:

```
import codecs, os, ast;__pyfile = codecs.open('''/Users/guilhermesalome/pyabYMoV''', encoding='''utf-8''');__code = __pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''/Users/guilhermesalome/pyabYMoV''');__block = ast.parse(__code, '''/Users/guilhermesalome/test.py''', mode='exec');__last = __block.body[-1];__isexpr = isinstance(__last,ast.Expr);__block.body.pop() if __isexpr else None;exec(compile(__block, '''/Users/guilhermesalome/test.py''', mode='exec'));eval(compile(ast.Expression(__last.value), '''/Users/guilhermesalome/test.py''', mode='eval')) if __isexpr else None
<_ast.Expr object at 0x103f25320>
```

Interestingly, it does not happen if I select just 1 line, and send it.

**Comment by galaunay** [comment]
Where are you getting this noise exactly, in the python shell ?

Could you try without Elpy, to see if it can be related to `python.el`
(just disable elpy with `M-x elpy-mode` and retry).

**Comment by Salompas** [comment]
Yes, in the python interpreter/shell. I open a python file, and then do `C-c C-z` to open the interpreter/shell, and then use `C-c C-c` to send the entire buffer or marked regions. Whenever I send more than one line I get that noise.

**Comment by galaunay** [comment]
And what happen if you deactivate elpy ?

**Comment by Salompas** [comment]
@galaunay it does not completely solve the issue, there is still noise, but it does diminish a bit (see below).

<img width="648" alt="screenshot 2018-08-27 07 17 33" src="https://user-images.githubusercontent.com/7663115/44657029-5981ce80-a9c9-11e8-8f4c-4c9eb6e2c080.png">

The first paragraph full of noise is with elpy-mode on, the second paragraph full of noise is with elpy-mode off.

**Comment by atreyasha** [comment]
Hello, I just wanted to comment on this issue and add a possible suggestion.

Usually when working with a python REPL, I like to return to some definitions of classes/functions and just edit them on the console for quick testing. This would not be possible with the current elpy python shell configuration because inputs of classes and functions are read by the console as files rather than strings inside the console. This also explains the "weird" history entries.

For this, I would propose developing a user-defined condition in elpy, similar to `elpy-shell--enable-echo`. Here, the user can basically define whether longer commands sent to the REPL should be stored within the python console's history as re-accessible strings for future testing directly within the REPL.

For this, I would like to draw focus to the function `elpy-shell--python-shell-send-string-echo-advice` within `elpy-shell.el`:

https://github.com/jorgenschaefer/elpy/blob/a1002f3682fe071652eb935e5c7c7de09c5ff2e1/elpy-shell.el#L585-L592

Notice that we already have a string containing the formatted input, namely `append-string`. So why don't we just define another function which appends the variable `append-string` to the local python/ipython history log?

I believe this would give elpy additional advantage in allowing users to choose and tailor their python IDE experience with emacs. If this is still relevant to anyone, please hit me up. I would be happy to develop this myself and submit a PR. I am new to emacs, so I need to get my hands a bit dirty first with elisp.

**Comment by galaunay** [comment]
It would be nice indeed to be able to store some of the code send to the shell in the history.

I had a quick look to the way the shell history was working last time, but I couldn't find a proper way to modify the shell history. In my opinion, this is what is missing to implement a better history support in Elpy: a way to interact and modify the shell history from outside.

ps: you can still access the shell history in the "Emacs' way" using `comint-previous-input`,  `comint-backward-matching-input`, `comint-dynamic-list-input-ring` and `comint-previous-matching-input-from-input`.

**Comment by atreyasha** [comment]
Thank you @galaunay for the feedback, and good to know that this feature might be useful for others as well. In terms of ipython, the user history log is located at `~/.ipython/profile_default/history.sqlite", at least for my system.

I believe it would be possible to execute a sql-command directly from elisp, which could essentially append the variable `append-string` from `elpy-shell.el` directly after the execution of the command. Then, the user would be able to access the appended command by going to a previous history item. One limitation could be that the sql command could add to delay in execution, but I guess that can only be verified empirically.

I attempted to use the aforementioned `comint-*` commands but was unable to recover the commands sent to the repl. Maybe I made some mistake, feel free to correct.

**Comment by galaunay** [comment]
> I attempted to use the aforementioned comint-* commands but was unable to recover the commands sent to the repl. Maybe I made some mistake, feel free to correct. 

You are right, my mistake, it doesn't seems to work with code sent from the script.

> I believe it would be possible to execute a sql-command directly from elisp, 

I am happy to help implement that, but it may end up being quite complicated to maintain (sql + need to support ipython, jupyter and python).

Would it be a viable solution to make the `comint-...` commands work instead ?

**Comment by galaunay** [comment]
It would be nice if you could try PR #1684 and tell me if it works for you as well
(instructions on how to install Elpy from a specific branch are available [here](https://elpy.readthedocs.io/en/latest/introduction.html#manually-from-sources) if necessary).

The only problem I still have with this PR is that it may not be a good idea to add massive pieces of code to the history (if a user is sending a big classe definition for example).
It could be annoying for some users to pollute their history with inputs of hundred of lines.
We will have to find a solution for that...

Also, my opinion is that this feature (adding inputs to history) should be integrated in `python.el` instead of in Elpy. I was planning to do it (some day) but if you still want to get your hands in Elisp, it could be an interesting task. However, `python.el` is part of Emacs, so making PR there may be more demanding.
If you choose to go that way and need some help, let me know.

**Comment by atreyasha** [comment]
Hello, I tested PR #1684 and I was able to retrieve the sent strings via `comint` within my python repl. However, emacs throws some errors which are listed below:

```
Output from Backend

There was some unexpected output from the Elpy backend. This is usually not a
problem and should usually not be reported as a bug with Elpy. You can safely
hide this buffer and ignore it. You can also see the output below in case there
is an actual problem.

Output
/home/shankar/.emacs.d/elpy/rpc-venv/bin/python: Error while finding module specification for 'elpy.__main__' (ModuleNotFoundError: No module named 'elpy')
```

Following is my elpy-configuration:

```
Elpy Configuration

Emacs.............: 26.3
Elpy..............: Not found (Python), 1.31.0 (Emacs Lisp)
Virtualenv........: None
Interactive Python: ipython 7.8.0 (/home/shankar/.local/bin/ipython)
RPC virtualenv....: rpc-venv (/home/shankar/.emacs.d/elpy/rpc-venv)
 Python...........: python 3.7.4 (/home/shankar/.emacs.d/elpy/rpc-venv/bin/python)
 Jedi.............: 0.15.1
 Rope.............: 0.14.0
 Autopep8.........: 1.4.4
 Yapf.............: 0.28.0
 Black............: 19.3b0
Syntax checker....: flake8 (/home/shankar/.local/bin/flake8)

You have not activated a virtual env. While Elpy supports this, it is often a
good idea to work inside a virtual env. You can use M-x pyvenv-activate or M-x
pyvenv-workon to activate a virtual env.

The Python interpreter could not find the elpy module. Please report to:
https://github.com/jorgenschaefer/elpy/issues/new.
```

Relevant system details:

```
GNU Emacs 26.3 (Distribution: spacemacs develop branch)
Arch Linux 5.3.5
```

**Comment by galaunay** [comment]
Elpy complains because it is not finding where its python files are stored.
So you may need to update the `elpy-rpc-pythonpath` variable:
``` elisp
(setq elpy-rpc-pythonpath "/path/to/elpy/folder")
```
and restart the RPC with `(M-x elpy-rpc-restart)`.

Hopefully it should work after that.

> Perhaps we could set a user-defined variable within elpy, where the user can turn this feature on if she/he wishes to have the history saved in the comint ring? IMO, that would still comply with the philosophy of customization within emacs. If you are fine with this suggestion, I could add this feature to the PR.

I try as much as possible to avoid adding new options to Elpy (there is already quite a lot of them) but it seems quite necessary in this case. 
I will finish the PR as soon as possible (I still need to update the doc and write some tests to cover the changes).

**Comment by atreyasha** [comment]
@galaunay tested this feature on the latest `elpy` release and works wonderfully, thank you!

**Comment by galaunay** [comment]
Thanks for the feedback.
I am closing this then.
Re-open if necessary.
