### ISSUE TITLE
Policy regarding python.el bugs

### ISSUE THREAD

**Issue by memeplex** [jorgenschaefer/elpy#1433]
This is not a report but a question about what to report.

When an issue in python.el is found what is the elpy policy? Does it keep a list of "python.el fixes" (advices, overwrites, etc)?

I'm asking this because the release frequency of python.el, being tied to emacs release schedule, is much slower than that of elpy and keeping workarounds in the meantime could make sense.

**Comment by galaunay** [comment]
I personally try to avoid as much as possible python.el fixes in Elpy (when it is not too bad obviously...).
It would make maintaining Elpy more difficult, especially because we try to support a decent range of Emacs versions (and so python.el versions).

@jorgenschaefer may have another opinion on the question though.

**Comment by jorgenschaefer** [comment]
I have the same opinion as @galaunay

**Comment by memeplex** [comment]
Thank you for clarifying that! I have a few ipython.el patches and I was in doubt regarding opening issues for them here.
