### ISSUE TITLE
[request] can we bring some goodies from vscode to elpy?

### ISSUE THREAD

**Issue by kirk86** [jorgenschaefer/elpy#1473]
Hi, thanks for creating elpy.
I was wondering if it is possible to integrate some features of vscode into elpy.
For instance the debugging and live code sharing capabilities would be pretty useful for many developers. 

Also since [vscode](https://github.com/Microsoft/vscode) is open source I presume it would make things easier in terms of translating whatever they have written in electron/js into elpy?

**Comment by galaunay** [comment]
Hi, 
New ideas to improve Elpy are always welcome !

Regarding debugging, nothing has been added in Elpy because `python.el` already offers debugging capabilities (see the [doc](https://www.emacswiki.org/emacs/PythonProgrammingInEmacs#toc29)). You can try the functionality by adding `import pdb; pdb.set_trace()` somewhere in your code (or just `breakpoint()` is your are using `python>3.7`).

Regarding code sharing, Emacs allows [collaborative editing](https://www.emacswiki.org/emacs/CollaborativeEditing).  I never really tried, but I think [togetherly](https://github.com/zk-phi/togetherly/) is the more up to date solution ATM.

Is it what you were looking for ?

**Comment by galaunay** [comment]
Completion should definitely works inside nested functions and classes.
The completion candidates can take a while to appear in some situtations, but it should not slow down Emacs.

The first thing to try would be to update everything: elpy, company, and the python packages that elpy needs (you can update them in `M-x elpy-config`).

If completion is still broken, could you open a new issue with your configuration and a minimal example, so we can have a look ?

**Comment by kirk86** [comment]
@galaunay thanks so much for you help and guidance.

> could you open a new issue

I will do and try to provide some examples.
I'm closing this issue to keep things clean.
