### ISSUE TITLE
Enhancement proposal: pyls support

### ISSUE THREAD

**Issue by saltycraig** [jorgenschaefer/elpy#1478]
After reading the following blog post at [vxlabs](https://vxlabs.com/2018/06/08/python-language-server-with-emacs-and-lsp-mode/), I wondered if there was thought about integrating or supporting the python language server as a completion/doc backend. The author mentions pyls does use jedi on the backend but in their experience this setup provided better completions that elpy. Has anyone tested this out? I could not get it running in Windows environment, and I haven't the time to try it out on linux/os x at the moment.

Proposal, then: 
Support retrieving completions from pyls in some way to possibly enhance/replace the results received via jedi interface.

**Comment by jorgenschaefer** [comment]
A great deal of Elpy is basically implements something like the language server protocol using JSON-RPC. I'm all in favor of replacing this code with something more standardized.

**Comment by memeplex** [comment]
I think this can be closed as a dup of https://github.com/jorgenschaefer/elpy/issues/1524. This report is older than mine but I think https://github.com/jorgenschaefer/elpy/issues/1524 is more clear about the intention of replacing the current backend with a language server in order to avoid duplication.

**Comment by galaunay** [comment]
@memeplex  I agree.
Discussion can continue in #1524
