### ISSUE TITLE
Ipython WARNING: your terminal doesn't support cursor position requests (CPR).

### ISSUE THREAD

**Issue by SVA2121** [jorgenschaefer/elpy#1491]
# Summary
Hello, I am quite new at elpy and emacs in general. I am trying to set it up to work with the ipython shell interpreter. However, whenever I run a command (with C-c C-y e for ex), the Ipython terminal is opened without the cursor and proper [In], [Out] messages. 

![image](https://user-images.githubusercontent.com/36765577/47968654-52cca300-e06d-11e8-9e44-1833e7790f7b.png)

# My configuration
--Ubuntu 18.04
--Emacs 26.1
--Elpy 1.26.0
--IPython 3.6.6

## Result of `(elpy-config)`
```
# Paste it here
```
![image](https://user-images.githubusercontent.com/36765577/47968693-bfe03880-e06d-11e8-8c37-c6c3d843cd8d.png)

## Elpy configuration in my init.el
```
# Paste it here
```

(elpy-enable)
(setq elpy-rpc-python-command "python3")
(setq python-shell-interpreter "ipython"
      python-shell-interpreter-args "-i")

**Comment by galaunay** [comment]
Hi, 

It is recommended to use Jupyter instead of ipython with Elpy (see Elpy's doc on that [here](https://elpy.readthedocs.io/en/latest/ide.html#interpreter-setup)).

But if you still want to use ipython, you will need to add the `--simple-prompt` argument, like this:
```Elisp
(setq python-shell-interpreter "ipython"
      python-shell-interpreter-args "-i --simple-prompt")
```

Let me know if it fixes your issue !

**Comment by SVA2121** [comment]
That worked! Thank you very much.
