### ISSUE TITLE
Completion stop working

### ISSUE THREAD

**Issue by Yevgnen** [jorgenschaefer/elpy#1502]
# Summary
After a 'recent' update of `elpy`, completion stop working after working in a buffer for several minutes. Although I look into the recent commits but seems that they are unrelated...

Accidentally I found that so many `Jedi` processes are spawned like

<img width="1280" alt="screen shot 2018-11-27 at 14 00 43" src="https://user-images.githubusercontent.com/16749790/49062026-98842200-f24d-11e8-90a2-ef46dfa3588a.png">

# Steps to reproduce
Not exactly known how, but always happened after I edit a file for several minutes.

# My configuration
## OS
`macOS 10.14.1`

## Result of `(elpy-config)`
```

Virtualenv........: one (/usr/local/var/pyenv/versions/one)
RPC Python........: 3.6.6 (/usr/local/var/pyenv/versions/one/bin/python)
Interactive Python: ipython (/usr/local/var/pyenv/versions/one/bin/ipython)
Emacs.............: 26.1
Elpy..............: 1.26.0
Jedi..............: 0.13.1
Rope..............: Not found (0.11.0 available)
Autopep8..........: Not found (1.4.3 available)
Yapf..............: Not found (0.25.0 available)
Black.............: Not found (18.9b0 available)
Syntax checker....: flake8 (/usr/local/var/pyenv/versions/one/bin/flake8)

```

## Elpy configuration in my init.el
```
# Paste it here
(use-package elpy
  :ensure t
  :diminish elpy-mode
  :after python
  :init
  (add-hook 'python-mode-hook (lambda () (setq-local company-idle-delay 0.1)))

  (setq elpy-modules
        '(elpy-module-company
          elpy-module-eldoc
          elpy-module-pyvenv
          elpy-module-sane-defaults)
        elpy-shell-echo-input nil
        elpy-shell-echo-output 'when-shell-not-visible)

  (add-hook 'elpy-mode-hook #'eval-sexp-fu-flash-mode)

  :config
  (elpy-enable)

  (unbind-keys :map elpy-mode-map '("C-c C-x" "C-c C-k" "C-c C-e"))
  (custom-set-variables '(elpy-shell-command-prefix-key "C-c C-e")))
```

## Emacs Version
`GNU Emacs 26.1 (build 2, x86_64-apple-darwin18.0.0, Carbon Version 158 AppKit 1671) of 2018-10-29`

**Comment by Yevgnen** [comment]
The process issue maybe related to `Jedi`. After resintall a `jedi==0.12.1`, the completion still has problem. While `elpy-config` find the right version of `python`, it can not complete objects from the `site-packages` in that environment. Completion of builtins works fine thought.


```
Elpy Configuration

Virtualenv........: one (/usr/local/var/pyenv/versions/one)
RPC Python........: 3.6.6 (/usr/local/var/pyenv/versions/one/bin/python)
Interactive Python: ipython (/usr/local/var/pyenv/versions/one/bin/ipython)
Emacs.............: 26.1.90
Elpy..............: 1.26.0
Jedi..............: 0.12.1 (0.13.1 available)
Rope..............: Not found (0.11.0 available)
Autopep8..........: Not found (1.4.3 available)
Yapf..............: Not found (0.25.0 available)
Black.............: Not found (18.9b0 available)
Syntax checker....: flake8 (/usr/local/var/pyenv/versions/one/bin/flake8)
```

**Comment by galaunay** [comment]
Regarding the numerous jedi sub-processes, I guess it is related to #1481.

The problem you have with completing objects from `site-packages` sounds like another issue.

Just to check, are you sure the virtual environnement have access to the global `site-packages` ?
From the pyenv doc, it uses pyvenv to manage virtualenv, so there should be a `pyvenv.cfg` file somewhere with an option `include-system-site-packages` set to `true`.

**Comment by AkashGanesan** [comment]
I have the same problem as well.  I upgraded recently and I no longer have completions.  I also downgraded Jedi and it still doesn't complete.

`Virtualenv........:  (/home/akash/learn/rl/hw5/)
RPC Python........: 3.6.7 (/home/akash/learn/rl/hw5/bin/python)
Interactive Python: jupyter (/home/akash/learn/rl/hw5/bin/jupyter)
Emacs.............: 25.2.2
Elpy..............: 1.27.0
Jedi..............: 0.12.0 (0.13.1 available)
Rope..............: 0.11.0
Autopep8..........: 1.4.3
Yapf..............: 0.25.0
Black.............: 18.9b0
Syntax checker....: flake8 (/home/akash/learn/rl/hw5/bin/flake8)`

I also don't use system-wide packages (flag's set to false).  I use Jupyter 

`Jupyter console 6.0.0
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
IPython 7.2.0 `

I get completions on python files but not on the interpreter which I used to get.  Here is my .emacs file (also, I didn't know if I wanted a new issue since it seems identical).

`(elpy-enable)

;; ;; (setq python-shell-interpreter "ipython"
;; ;;       python-shell-interpreter-args "-i --simple-prompt")

(setq python-shell-interpreter "jupyter"
      python-shell-interpreter-args "console --simple-prompt"
      python-shell-prompt-detect-failure-warning nil)

(add-to-list 'python-shell-completion-native-disabled-interpreters
             "jupyter")

(setq elpy-shell-use-project-root t)

;; Add yasnippet support for all company backends
;; https://github.com/syl20bnr/spacemacs/pull/179
(defvar company-mode/enable-yas t
  "Enable yasnippet for all backends.")

(defun company-mode/backend-with-yas (backend)
  (if (or (not company-mode/enable-yas) (and (listp backend) (member 'company-yasnippet backend)))
      backend
    (append (if (consp backend) backend (list backend))
            '(:with company-yasnippet))))

;; (setq company-backends (mapcar #'company-mode/backend-with-yas company-backends))
             

(add-hook 'python-mode-hook
          (lambda ()
            ;; explicitly load company for the occasion when the deferred
            ;; loading with use-package hasn't kicked in yet
            (company-mode)
            (add-to-list 'company-backends
                         (company-mode/backend-with-yas 'elpy-company-backend))))
`

**Comment by immerrr** [comment]
It is a bug in jedi: https://github.com/davidhalter/jedi/issues/1242

**Comment by avocadoras** [comment]
What is the proper way to fix this?  I can only get jedi to autocomplete in a buffer when
```elisp
(setq elpy-rpc-backend "jedi")
```
Although, from my understanding, Elpy works out of the box.

See my `M-x elpy-config`
```
Virtualenv........: None
RPC Python........: 3.7.2 (/Users/jr/.pyenv/shims/python)
Interactive Python: python (/Users/jr/.pyenv/shims/python)
Emacs.............: 26.1
Elpy..............: 1.28.0
Jedi..............: 0.13.3
Rope..............: Not found (0.14.0 available)
Autopep8..........: Not found (1.4.3 available)
Yapf..............: Not found (0.26.0 available)
Black.............: Not found (19.3b0 available)
Syntax checker....: flake8 (/Users/jr/.pyenv/shims/flake8)
```
