### ISSUE TITLE
Interpreter shows wrong line number (not the same issue as 983)

### ISSUE THREAD

**Issue by steve-the-bayesian** [jorgenschaefer/elpy#1505]
# Summary
Interpreter shows the wrong line number:

# Steps to reproduce
Here's a function:

```
def exponential_smoothing(x, present_weight):
    ''' Compute an exponential smooth of a data series x.

    Args:
      x:  The series to be smoothed.
      present_weight: The weight to put on the present time period.

    Returns:
      A smoothed series 's' of the same length as x, defined according to

        s[t] = a * x[t] + (1-a) * s[t-1]

    where a is 'present_weight'.
    '''
    s = []
    s[0] = x[0]
    i = 1;
    while np.isnan(s[i - 1]):
        s[i] = x[i];
        i += 1
    for index in range(i, len(x)):
        s[index] = present_weight * x[i] + (1 - present_weight) * s[i - 1]
    return s

```
Here's some test 
import numpy as np
x = np.random.randn(10)
y = exponential_smoothing(x, .01)

The 'def' line of my function begins on line 300 of a larger module.
With elpy turned off  (i.e. with the line (elpy-enable) commented out in my .emacs file) I send my function to the interpreter with C-r.  Then I run the test code, which produces the error message:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/steve/code/python/Rlib/Rlib.py", line 315, in exponential_smoothing
    s[0] = x[0]

With elpy turned on (un-comment (elpy-enable) in .emacs) I send the function to the interpreter by C-return.  Then I send the same test code and get 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/steve/code/python/Rlib/Rlib.py", line 16, in exponential_smoothing
    Args:
IndexError: list assignment index out of range

It is the same error, but the line number is reported counting from the def line instead of from the top of the file. 

# My configuration
## OS
Ubuntu
No LSB modules are available.                                                    Distributor ID: Ubuntu                                                           Description:    Ubuntu 18.04.1 LTS                                               Release:        18.04                                                            Codename:       bionic
--

## Result of `(elpy-config)`
```
Elpy Configuration

Virtualenv........: None
RPC Python........: 2.7.15 (/usr/bin/python)
Interactive Python: python3 (/usr/bin/python3)
Emacs.............: 25.2.2
Elpy..............: 1.26.0
Jedi..............: 0.13.1
Rope..............: Not found
Autopep8..........: 1.4.3
Yapf..............: 0.25.0
Black.............: Not found
Syntax checker....: flake8 (/home/steve/.local/bin/flake8)

You have not activated a virtual env. While Elpy supports this, it is often a
good idea to work inside a virtual env. You can use M-x pyvenv-activate or M-x
pyvenv-workon to activate a virtual env.

The black package is not available. Commands using this will not work.

[run] python -m pip install --user black

Options

`Raised' text indicates buttons; type RET or click mouse-1 on a button to invoke
its action.  Invoke [+] to expand a group, and [-] to collapse an expanded
group.  Invoke the [Group], [Face], and [Option] buttons below to edit that item
in another window.

[+]-- Group Elpy
[+]-- Group Python
[+]-- Group Virtual Environments (Pyvenv)
[ ]-- Group Completion (Company)
[+]-- Group Call Signatures (ElDoc)
[+]-- Group Inline Errors (Flymake)
[ ]-- Group Snippets (YASnippet)
[+]-- Group Directory Grep (rgrep)
[+]-- Group Search as You Type (ido)
[+]-- Group Django extension
[+]-- Group Autodoc extension

```

## Elpy configuration in my init.el    (.emacs actually  -- hopefully that does not make a difference)
```
(elpy-enable)
(setq elpy-rpc-pyton-command "python3")

```

**Comment by galaunay** [comment]
Thanks for reporting,
indeed Elpy just send the region as a string, which mess up with the line numbers.
Python-mode is smarter about it.

In this example:
```Python 
1 def foo(a, b):
2     c = b + a
3     return c
4
5 def bar(a, b):
6     c = b - a     # <-- cursor here
7     c = d
8     return c
```
Elpy would send:
```Python
1 def bar(a, b):
2    c = b - a 
3    c = d
4    return c
```
(and report an error on line 3)
while python-mode would send:
```Python 
1 
2 
3 
4 
5 def bar(a, b):
6     c = b - a  
7     c = d
8     return c
```
(and report an error on line 7, as expected)

@jorgenschaefer, would it make sense to use python-mode function to extract substrings (`python-shell-buffer-substring`) instead of Elpy's one (`elpy-shell--region-without-indentation`).
The former seems more elaborated. 
From the documentation:
```
(python-shell-buffer-substring START END &optional NOMAIN)

This is a wrapper over `buffer-substring` that takes care of
different transformations for the code sent to be evaluated in
the python shell:
  1. When optional argument NOMAIN is non-nil everything under an
     "if __name__ == '__main__'" block will be removed.
  2. When a subregion of the buffer is sent, it takes care of
     appending extra empty lines so tracebacks are correct.
  3. When the region sent is a substring of the current buffer, a
     coding cookie is added.
  4. Wraps indented regions under an "if True:" block so the
     interpreter evaluates them correctly.
```

**Comment by steve-the-bayesian** [comment]
I'm seeing similar issues when debugging using pdb.  When I hit a breakpoint emacs puts the cursor k lines into the file instead  of k lines into the function.  I hope it is the same problem.

**Comment by steve-the-bayesian** [comment]
I'm curious about why more people haven't run into this bug.  It makes debugging python code significantly harder for me.  Is there a different debugging model I should be using that does not tickle this problem?

(My method, for the record, is to have a script open in one emacs frame, and python running in another).  I make a change in a function, put pdb.set_trace() nearby, put my cursor on the function name and hit C-return).

**Comment by galaunay** [comment]
I made a PR (#1520) to try to fix this issue.
Apparently it fixes the problem with pdb as well.

Could you try it to see if it fixes your issues properly ?

**Comment by steve-the-bayesian** [comment]
Cool!  Today is my birthday, and you've given me a present.  :)
I'll test this a bit later this evening.  Thanks for the effort.
s

**Comment by steve-the-bayesian** [comment]
How can I get the update on my system?  Thanks for fixing the bug.

**Comment by galaunay** [comment]
Sorry, I was not around those last days.

I just merged the PR into the main branch.
The problem should be fixed in the next Elpy release.

I close this issue for now, please re-open if the fix is not working for you.

**Comment by lihebi** [comment]
Hi, I think the change #1520 may cause undesired behavior for `elpy-shell-send-statement-and-step`.

Assume we have this code:

```python
def foo():
      1+1
      while True:
               2+2
```

When executing `elpy-shell-send-statement-and-step` on line 2, I expect just `"1+1"` is send to the shell, and I should see the output `2`. Similarly when executing the command on line 4, I expect `"2+2"` is sent and prints out `4`. That is the old behavior.

But now, if the statement under execution is indented, `python-shell-buffer-substring` will wrap the string with `"if True"` and a couple of `\n`, thus becoming `if True:\n\n   1+1`, where the number of `\n` is the indentation level of the statement.

The downsides of this new behavior:
1. It does not print out the result of the statement, because it is wrapped with the conditional stmt
2. There can be a lot of empty lines inserted into the shell REPL, thus pretty annoying, like this:

```
In [7]: if True:
   ...: 
   ...: 
   ...: 
   ...: 
   ...:             2+2
In [8]: 
```

**Comment by galaunay** [comment]
I don't use echoing inputs ans outputs so I missed this one.
Thanks for raising that.

I found a solution regarding point 2 (#1534).

Regarding point 1, it is a bit more complicated...
When python.el sends code that contains multiple lines to the shell, it is not sent as a string, but as a file that is executed.
Because the code is not run "interactively", it is difficult to get the result output back.

I am sure we can find a solution to address this, but I would need to know exactly what is your use of this feature.

**Comment by lihebi** [comment]
Thanks for looking into this.

I actually use this command quite often, and I think this is a basic need: to be able to evaluate an expression, or apply a function to some inputs and observe the return. It's like you have a lisp S-exp in your program somewhere, and you want to evaluate it (`C-x C-e`). This can be achieved by typing the exact expression and function calls in the REPL, but that is tedius.

**Comment by lihebi** [comment]
> When python.el sends code that contains multiple lines to the shell, it is not sent as a string, but as a file that is executed. Because the code is not run "interactively", it is difficult to get the result output back.

`elpy-shell-send-file` does exactly that. It tests whether the last statement is an expression. If yes, it will remove that expression, and evaluate it separately. That is why the results are printed in the REPL output in the old behavior.

The reason why the new code does not have this, is simply that the last statement is no longer an expression, but a if-statement.

**Comment by lihebi** [comment]
I looked into this, and got a solution that seems to work, and also retains the correct line numbers (most of the time, see below for exception). I only did some light test though. Here is a complete description about it. See if it is desired.

Since the values are outputed only when the last statement is an expression (which is the correct behavior), the fix would be to strip out "if True:" before sending into `python-shell-send-string`, like this:

```elisp
(defun elpy-shell--strip-iftrue (str)
  "Strip ``if True:'' (first try)."
  (replace-regexp-in-string "^if True:$" "" str))
```

However, this does not do the trick yet. To support multi-line code, the indentation must be taken care of. This can be done through reusing the old code of function `elpy-shell-send-statement-and-step` (see 0ab7f48)

```elisp
(defun elpy-shell--strip-iftrue (str)
  "Strip both ``if True:'' and take care of indentation."
  (let ((region (replace-regexp-in-string "^if True:\n" "" str))
        (indent-level nil)
        (indent-tabs-mode nil))
    (with-temp-buffer
      (insert region)
      (goto-char (point-min))
      (while (< (point) (point-max))
        (cond
         ((or (elpy-shell--current-line-only-whitespace-p)
              (python-info-current-line-comment-p)))
         ((not indent-level)
          (setq indent-level (current-indentation)))
         ((and indent-level
               (< (current-indentation) indent-level))
          (error (message "X%sX" (thing-at-point 'line)))))
        (forward-line))
      (indent-rigidly (point-min)
                      (point-max)
                      (- indent-level))
      (untabify (point-min) (point-max))
      (buffer-string))))
```

Up to now, the functionality of evaluating any expressions is back. And it can also correctly work out the line numbers! But .. only when sending multi-line code. Single line code is returned as `"\n\n\n\n  code"` by `python-shell-buffer-substring`, but it is still single-line code, as `python-shell-send-string` uses `".\n+."` to check. Such single-line code is directly evaluated, instead of writing to a file.  A hack for this is to modify the string so that it is treated as a multi-line one. For example, modify the last line of above function:

```elisp
(defun elpy-shell--strip-iftrue (str)
  ...
  (concat "1\n" (buffer-string)))
```

This would work, but would also create runtime overhead, and also the extra statements need to be taken care of by the output echo filter so that the REPL looks clean and trasparent to users. I think this is not a big deal, as when users are executing a single line, they know the line number. So maybe forget about this, or some other suggestions?

This function needs to be used in the two affected functions `elpy-shell-send-statement-and-step` and `elpy-shell--send-region-or-buffer-internal` like this:

```elisp
(defun elpy-shell-send-statement-and-step ()
  ...
  (python-shell-send-string
   (elpy-shell--strip-iftrue
    (python-shell-buffer-substring beg end))))
(defun elpy-shell--send-region-or-buffer-internal (&optional arg)
  ...
  (let ((region (elpy-shell--strip-iftrue
                 (python-shell-buffer-substring
                  (region-beginning) (region-end)))))
    (python-shell-send-string region)))
```

**Comment by galaunay** [comment]
Thanks a lot for investigating this. 
I completely missed `elpy-shell-send-file` before you pointed it at me.

I couldn't make your PR work, is it working on your side ?

In the meantime, I manage to make `elpy-shell-send-file` ignore the `it True:` statement (see PR #1534).It would be very nice if you could try it and give me your opinion.

**Comment by lihebi** [comment]
Cool, your PR works. Forget about mine then.
