### ISSUE TITLE
Completion of "os.ver" results in "os.version" and "os.version_info" which is incorrect

### ISSUE THREAD

**Issue by bgoodr** [jorgenschaefer/elpy#1552]
# Summary

First off, thanks again for your tremendous effort on this package. I would not ever want to develop in python without it!!!

The problem I'm facing: I'm expecting (probably a bit too much!) that elpy will do completion based upon the object to the left of the ".". Such as "sys.ver" will know that "sys" is the module, and complete to items within the "sys" package alone, but never to things in other modules, such as the "sys" module. But I speculate that something confuses "os" and "sys" as described below (or I have misconfigured the company backend?).

# Steps to reproduce

Open up a file.py in Emacs and insert in:

```
import os
import sys
print(sys.version)
print(sys.version_info)
for x in os.__dict__:
    print(x)
# os.ver
y = [x for x in os.__dict__ if "ver" in str(x)]
print(y)
# os.ver
```

If you run the file, you will see that "y" is empty, proving that the sys module does not have any attribute with "ver" in the stringified form of the attribute.

Then, uncomment out the line with "os.ver" on it. 

Put the cursor (point) right after the "r" in "os.ver" at the very end of that line. Type C-M-i (bound to elpy-company-backend currently). It shows this:

![screenshot1](https://i.imgur.com/ukcKi1Z.png)

Now, if instead I had "sys.ver" instead of "os.ver" in the above, then it would be correct. 

This may be user error, or a company-mode bug, and not an elpy-mode bug, but I have to start here given that C-M-i is bound to an elpy function.

# My configuration
## OS

```
Distributor ID:    CentOS
Release:    7.2.1511
```

## Result of `(elpy-config)`
```
Elpy Configuration

Virtualenv........: envpython3 (/wv/cal_scratch_nobackup_brentg_regr/conda/CentOS.7.2.1511.miniconda3/envs/envpython3)
RPC Python........: 3.7.2 (/wv/cal_scratch_nobackup_brentg_regr/conda/CentOS.7.2.1511.miniconda3/envs/envpython3/bin/python)
Interactive Python: python (/wv/cal_scratch_nobackup_brentg_regr/conda/CentOS.7.2.1511.miniconda3/envs/envpython3/bin/python)
Emacs.............: 25.3.1
Elpy..............: 1.28.0
Jedi..............: 0.13.3
Rope..............: 0.12.0
Autopep8..........: 1.4.3
Yapf..............: 0.26.0
Black.............: 18.9b0
Syntax checker....: flake8 (/wv/cal_scratch_nobackup_brentg_regr/conda/CentOS.7.2.1511.miniconda3/envs/envpython3/bin/flake8)

Options

`Raised' text indicates buttons; type RET or click mouse-1 on a button
to invoke its action.  Invoke [+] to expand a group, and [-] to
collapse an expanded group.  Invoke the [Group], [Face], and [Option]
buttons below to edit that item in another window.

[+]-- Group Elpy
[+]-- Group Python
[+]-- Group Virtual Environments (Pyvenv)
[+]-- Group Completion (Company)
[+]-- Group Call Signatures (ElDoc)
[+]-- Group Inline Errors (Flymake)
[+]-- Group Snippets (YASnippet)
[+]-- Group Directory Grep (rgrep)
[+]-- Group Search as You Type (ido)
[+]-- Group Django extension
[+]-- Group Autodoc extension
```

## Elpy configuration in my init.el
```
;; -*-mode: lisp-interaction; -*-

(defun bg-install-package (package)
  "Derived from code at https://realpython.com/blog/python/emacs-the-best-python-editor/ "

  ;; FINDING PACKAGE DEPENDENCIES:
  ;;
  ;; To see dependencies see
  ;; https://yoo2080.wordpress.com/2014/05/16/how-to-list-emacs-package-dependencies/
  ;; and do this inside a lisp-interaction buffer:
  ;;
  ;;    (pp package-alist)
  ;;
  ;; then you can search down to see what package depends upon what other
  ;; packages.  Often the .emacs.d directory gets out of whack so much that I
  ;; could not even reinstall deleted packages and so had to give up and just
  ;; remove all of .emacs.d and reinvoke emacs that then reinvoked calls to this
  ;; function to repair it.
 
  (require 'package)
  (add-to-list 'package-archives
           '("melpa" . "https://melpa.org/packages/"))
  (package-initialize)
  (when (not package-archive-contents)
    (package-refresh-contents))
  (unless (package-installed-p package)
    (package-install package)))

(bg-install-package 'elpy)
(elpy-enable)
```

**Comment by galaunay** [comment]
> The problem I'm facing: I'm expecting (probably a bit too much!) that elpy will do completion based upon the object to the left of the ".". Such as "sys.ver" will know that "sys" is the module, and complete to items within the "sys" package alone, but never to things in other modules, such as the "sys" module. But I speculate that something confuses "os" and "sys" as described below (or I have misconfigured the company backend?).

Elpy does provide completion based on the object before point. The problem is that Jedi (the completion backend Elpy uses) sometimes failed to analyse the code (no shame in that, Python code can be very difficult to analyse). Because of that, Elpy falls back to a more simple completion mechanism ([dabbrev](https://www.emacswiki.org/emacs/DynamicAbbreviations)) when jedi doesn't provide completion candidates.

So to describe what happens in your example:
- You are asking for a completion beginning by `ver` in the `os` module.
- Jedi fails to provide completion (because there is nothing beginning by `ver` in the `os` module).
- Elpy falls back to dabbrev completion.
- Dabbrev looks in the buffer for things beginning by `ver` and finds the string `version` and `version_info` at lines 3 and 4.
- Elpy offers those strings as completion.

As an illustration of this mechanism, you can try removing lines 3 and 4.
dabbrev will then also fail to find completion candidates and Elpy will not offer any completion for `os.ver` anymore.

There is no way ATM to deactivate this behavior. But if dabbrev completion is something you find really annoying, we can think about a solution.

If you have thoughts on how to improve the completion mechanism, we are always interested by new ideas as well :).

**Comment by bgoodr** [comment]
That is a most excellent answer!

Now that I know what they behavior is, I can know to work around it.
