### ISSUE TITLE
Does elpy support dynamic/runtime auto-completion for type/variable/function names?

### ISSUE THREAD

**Issue by hongyi-zhao** [jorgenschaefer/elpy#1846]
Hi,

Does elpy  support dynamic/runtime auto-completion for type/variable/function names, just
as the behavior showed by ipython/jupyter?

Regards,
HY

**Comment by galaunay** [comment]
If you mean completion in the interpreter itself, yes, and it should work out-of-the-box.

If you mean completion in the python script depending on what is loaded in the interpreter, yes as well, but it is not activated by default. You will need to add `(setq elpy-get-info-from-shell t)` to your configuration file ([Here](https://elpy.readthedocs.io/en/latest/ide.html?highlight=get-info#option-elpy-get-info-from-shell) is the relevant part of the documentation).

This feature is not activated by default because it can sometimes lead to Emacs freezing for a while (a problem I could not find a solution to...). Be aware that it can happen if you activate this.

**Comment by hongyi-zhao** [comment]
> This feature is not activated by default because it can sometimes lead to Emacs freezing for a while (a problem I could not find a solution to...).

Is there any other Emacs developer who can help to solve this problem?

**Comment by galaunay** [comment]
I would be happy to be able to improve this feature, but it happens very rarely (at least for me), and is quite difficult to reproduce, which make it difficult to fix.

If you could give some feedback on whether it happens for you or not and when, that would really help to track the problem down. If it happens, you can get back control on Emacs with a few `C-g`.

**Comment by hongyi-zhao** [comment]
Does this package support the latest git master version of Emacs? I will try to enable this option and provide feedback based on the problems encountered.

**Comment by galaunay** [comment]
Not officially, but I am using Elpy with Emacs 28 since it is available, and everything works fine.
