### ISSUE TITLE
elpy-doc can't find documentation for "import foo as bar"

### ISSUE THREAD

**Issue by Timothy-W-Hilton** [jorgenschaefer/elpy#397]
Minimal example:

import numpy as np
foo = np.random.rand(10)

C-c C-d on np.random.rand displays "No documentation found" in the minibuffer.  If I manually edit "Pydoc for: np.random.rand" to "Pydoc for: numpy.random.rand" it works nicely.

If I instead do 

import numpy 
foo = numpy.random.rand(10)

C-c C-d on numpy.random.rand displays the docs beautifully.  

config info:
Elpy Configuration

Virtualenv........: None
RPC Python........: 2.7.6 (/Users/tim/Library/Enthought/Canopy_64bit/User/bin/python)
Interactive Python: ipython (/Users/tim/Library/Enthought/Canopy_64bit/User/bin/ipython)
Emacs.............: 24.3.1
Elpy..............: 1.6.0
Jedi..............: 0.8.1-final0
Rope..............: 0.9.4 (0.10.2 available)
Syntax checker....: pyflakes (/Users/tim/Library/Enthought/Canopy_64bit/User/bin/pyflakes)

You have not activated a virtual env. While Elpy supports this, it is
often a good idea to work inside a virtual env. You can use M-x
pyvenv-activate or M-x pyvenv-workon to activate a virtual env.

The directory ~/.local/bin/ is not in your PATH, even though you do
not have an active virtualenv. Installing Python packages locally will
create executables in that directory, so Emacs won't find them. If you
are missing some commands, do add this directory to your PATH.

There is a newer version of Rope available.

[run] pip install --user --upgrade rope

The configured syntax checker could not be found. Elpy uses this
program to provide syntax checks of your programs, so you might want
to install one. Elpy by default uses flake8.

[run] pip install --user flake8

**Comment by jorgenschaefer** [comment]
Does this answer your question?

**Comment by rlvesco7** [comment]
To hopefully help others, I had a similar problem with getting documentation. The best, and most general, solution I found was to use the helm-dash package. Dash/Zeal are programs for mac/unix/windows that convert programming documentation to a searchable index. Helm-dash interfaces with this index to get instantaneous documentation results for any point in your buffer. You can set it to open your browser or eww. The upside is that this also work with your other languages, not just python. Also, the helm-dash package doesn't require to have dash/zeal installed.  See it in action: https://github.com/areina/helm-dash

**Comment by jorgenschaefer** [comment]
Lacking further information, I will close this issue. Please do not hesitate to re-open the issue or create a new one if you have further problems, and enjoy Elpy!

**Comment by steve-the-bayesian** [comment]
Sorry to reopen this acient thread, but I'm curious about the best way to view documentation in elpy.  Right now I cannot view it at all.  from this thread the advice seems to be "use rope instead."  But elpy defaults to Jedi in 2021, and the debate about jedi vs rope seems to have taken place in 2013, so I'm worried about missing out on features that jedi provides but rope does not.  
`help(object)` does not work (at least out of the box) because `help` wants to pipe its output through a pager.  `C-d` gives `no documentation found` even when asking for well documented objects (e.g. numpy).  

Accessing docs is such a fundamental feature that I can't believe it doesn't work in elpy.  What am I doing wrong?

**Comment by artsi0m** [comment]
I second previous post.
