### ISSUE TITLE
Elpy error: fixup_imports not enabled; install importmagic module

### ISSUE THREAD

**Issue by ChillarAnand** [jorgenschaefer/elpy#462]
Steps to reproduce the error:

1. Open emacs & activate venv which __doesn't have__ importmagic.
2. Try to import anything using `C-c RET` & it throws errors.
3. Now activate any other venv which __has__ importmagic installed & try to import anything.

If `importmagic` is installed systemwide this wont occur but I just thought of reporting it :eyes:

**Comment by jorgenschaefer** [comment]
This is because the first virtualenv started an RPC process for the current buffer, and won't be restarted when you switch the virtualenv. This same issue happens when you switch from a virtualenv without jedi/rope to one that does, the RPC process is not restarted by switching the virtualenv.

`M-x elpy-rpc-restart` should fix the situation.

Hm. Come to think of it, it would probably be a good idea to improve this lookup process. This would make a good addition to #461. But nothing that can happen before 1.7 is out I'm afraid :-)

**Comment by ChillarAnand** [comment]
can we do something like this?

    (add-hook 'pyvenv-post-activate-hook 'elpy-rpc-restart)

**Comment by jorgenschaefer** [comment]
You can do that if you like, but I would prefer not to do that in Elpy by default.

**Comment by ChillarAnand** [comment]
That makes sense. Thank You :smile:

**Comment by jorgenschaefer** [comment]
Thank _you_ for the report! :-)
