### ISSUE TITLE
Error initializing Elpy

### ISSUE THREAD

**Issue by abdulhaq-e** [jorgenschaefer/elpy#508]
I get the error quoted below, things were working fine, it must be a package update that caused this. I'm using `elpy` with Emacs Prelude but all Python related code has been removed in my config. By starting emacs with no settings using `emacs -Q` , the problem is solved and `elpy` works fine. I appreciate it if you help me debug this:

```
Error initializing Elpy

There was an error when trying to start the backend. Elpy can not work
until this problem is solved. The following lines were received from
Python, and might help identifying the problem.

** Message: pygobject_register_sinkfunc is deprecated (GstObject)
```

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report!

> `** Message: pygobject_register_sinkfunc is deprecated (GstObject)`

This means that something somewhere in your code, or in a library you use, is using `pygobject_register_sinkfunc`, which causes GObject to print some stuff to stdout. Which it shouldn't, really, but here we are.

If this only started after the last Elpy upgrade, you can try not enabling importmagic, which tends to cause all sorts of messages because it imports everything.

You can also try to avoid using whichever code is doing that. If you care for an adventure, you can also try the current development version of Elpy – it has some code to show such a message, but to keep working afterwards.

It is weird this only happens when your init file is loaded … not knowing what your init file does, I can't really begin to guess what might be causing this, though, I'm afraid. :-(

**Comment by abdulhaq-e** [comment]
After searching for a little bit, I couldn't find the library that was using this. Emacs Prelude is huge so more time is needed!

I already tried to start the adventure a few days ago by installing the development version. The Python module was easy to install but then I failed to install the Lisp package as I don't know how to do it. `Elpy` complained that the Lisp version doesn't match the Python version so I rolled back to the stable version. How do I cleanly install the package from the git repository? 

Thanks for your reply.

**Comment by jorgenschaefer** [comment]
You can remove the elpy package installed via `package-install`, e.g. `rm -rf ~/.emacs.d/elpy/elpy*`, and add the git repository to your `load-path`, together with a `(load "elpy")` in your `.emacs` before the `elpy-enable` call.

**Comment by jorgenschaefer** [comment]
I do hope to release a bugfix release of Elpy tomorrow, so if that's too much effort and you have the time, you can wait until then :-)

**Comment by jorgenschaefer** [comment]
Actually, I did the release now. Should be on the Elpy ELPA and on Marmalade, and on MELPA as well as MELPA Stable whenever they do their updates next.

**Comment by jorgenschaefer** [comment]
I assume this problem is solved. Please do not hesitate to open a new issue if you have any further problems, and enjoy Elpy :-)

**Comment by matrixise** [comment]
Hello, I have tested with the last version of Elpy (20160903.841) from the elpy repository.

```
Output from Backend                                                                                                                               

There was some unexpected output from the Elpy backend. This is                                                                                   
usually some module that does not use correct logging, but might                                                                                  
indicate a configuration problem.                                                                                                                 

Output                                                                                                                                            
** Message: pygobject_register_sinkfunc is deprecated (GstObject)   
```

Could you re-open this issue ?

Thank you

**Comment by jorgenschaefer** [comment]
> Could you re-open this issue ?

I could, if this were an issue with Elpy. As I explained above, this is some library the writes to stdout instead of using the official Python logging API. Elpy keeps working, it just lets you know that the library you are using is emitting stuff that might or might not be relevant to you. Elpy could not possibly know. If it's not relevant to you, you can safely ignore this. As it says in the text.

As far as I can see, this could be described as any of the following issues:
1) The library you are using should not just write to stdout/stderr but use the logging module
2) The library should not do anything just because it is being imported
3) importmagic should not import this library to provide import hints

I don't think (3) would be good, as it would limit importmagic's functionality. You can of course simply not use importmagic to avoid this. But for (1) and (2), please file a bug report with the respective library.
