### ISSUE TITLE
python-shell-interpreter-interactive-arg is ignored when using elpy-use-ipython in emacs 24.4

### ISSUE THREAD

**Issue by lancepantz** [jorgenschaefer/elpy#531]
After upgrading to 24.4, setting `python-shell-interpreter-interactive-arg` to "" no longer worked, and continued to pass "-i", causing an error when code using arparse was sent to the ipython interactive buffer. 

my elisp is pretty weak, but this looks like the culprit: https://github.com/jorgenschaefer/elpy/blob/master/elpy.el#L1351

I was able to work around this with the following manual declaration:

```elisp
(custom-set-variables
 '(elpy-interactive-python-command "ipython")
 '(elpy-rpc-python-command "python3")
 '(python-shell-interpreter "ipython")
 '(python-shell-interpreter-args "")
 '(python-shell-interpreter-interactive-arg ""))
```

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report!

This is an unfortunate interaction between customize, `elpy-use-ipython`, and your specific use case. Strictly speaking, there is no need for `elpy-use-ipython` to be called in 24.4 anymore, but Elpy does because it was a huge problem in 24.3 and before.

I'll look into this to not change variables if they have been changed already, thank you!

**Comment by pooyahub** [comment]
Could you also remove the description for the variable elpy-interactive-python-command from the documentation to avoid confusion? Thanks!
http://elpy.readthedocs.io/en/latest/ide.html#interactive-python
