### ISSUE TITLE
Why remove modeline lighter for company mode?

### ISSUE THREAD

**Issue by hotpxl** [jorgenschaefer/elpy#618]
On `elpy.el:2958`, why remove modeline lighter for company mode? I think company mode's lighter is showing which backend is currently active, and it's quite useful.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for noting this.

The mode line tends to be very crowded, drowning out a lot of information. I never considered the backend information to be very useful – in Elpy, you will always get the Elpy backend there, because Elpy does asynchronous checks and has to always feel responsible for Python buffers.

This is of course not useful when you use company mode in other modes, where more than one backend might be selected. Sadly, this is not something Emacs allows to be changed on a per-buffer basis easily.

Would it help if Elpy would make the mode line cleanup optional with a custom option?

**Comment by hotpxl** [comment]
Yes. An option would be fine. Thanks.

**Comment by hotpxl** [comment]
I suppose it's going to be in `v1.9.0`?

**Comment by jorgenschaefer** [comment]
Probably, depending on when I have the time to work on it :-) Please leave the issue open so I don't forget, thank you!

**Comment by hotpxl** [comment]
Hi. I don't mean to rush you. But could you just add a quick switch to turn off this behavior? Sometimes I want to see specific statuses.

**Comment by jorgenschaefer** [comment]
No worries, you can't rush me. It's on my list. I work on issues when I have time. Pull requests welcome. :-)

Elpy has a release scheduled for the end of this month, so it's likely I'll work on it a bit the coming days. But I do not generally promise what I work on. In the meantime, you can remove `elpy-module-company` from `elpy-modules`. Look at the function source code to see what other customizations it does.

Hope this helps!
