### ISSUE TITLE
auto completing self with equal operator

### ISSUE THREAD

**Issue by dccmmccd1** [jorgenschaefer/elpy#632]
Hey,

First of all I'd like to say that I'm very pleased with elpy and think it improved my efficiency. One this bugs me though. When implementing a method, if I write "sel" it auto completes it to "self=" (not "self" as I would expect). So if I type the characters <sel.> (4 characters ending with dot) I get "self=." which is quite annoying since it prevents the autocompletion of all the class members. If I then delete the "=" and retype the dot, then I get all the class members as possible completions. 

I'm using the following versions:
emacs - 24.4.1
elpy - 1.8.1
company - 20150727.1415

I'm setting company-backends to (elpy-company-backend), and elpy-rpc-backend to jedi.
Any idea what's going on?

**Comment by arvids** [comment]
I have the same issue in that my completions in python seem to favour ending with = but it only does so if I have typed that variable in the args of a function, ( def foo(bar):  ba + tab -> bar= , fo + tab -> foo )
I have emacs 24.5.1, elpy 1.8.1, company version 0.9.0-cvs and using jedi as rpc-backend.

**Comment by arvids** [comment]
This seems to be the same issue as #613

**Comment by jorgenschaefer** [comment]
Thank you for the report! As @arvids correctly noticed, this is sadly a known problem in Jedi – it thinks that the `self` in this case is a named argument to the function as opposed to a local variable, which breaks.

If you have updates on this, in particular reproduction steps, please update #613. And sorry for the annoyance caused by this.
