### ISSUE TITLE
Document C-return's interaction with nested statements

### ISSUE THREAD

**Issue by ChillarAnand** [jorgenschaefer/elpy#642]
```python
if True:
    print('elpy')
```

If above two statements are sent to shell, it is throwing indentation error.

**Comment by jorgenschaefer** [comment]
What do you mean with "are sent to shell", exactly? What command are you using?

Is this an instance of [this bug](https://github.com/jorgenschaefer/elpy/pull/619#issuecomment-127957058), maybe?

**Comment by ChillarAnand** [comment]
> What do you mean with "are sent to shell", exactly? What command are you using?

I am sending two statements using `C-<RET>`.

> Is this an instance of this bug, maybe?

 We are using `python-shell-send-string` but not `python-shell-buffer-substring`?

**Comment by jorgenschaefer** [comment]
Ah, thanks for the context.

The problem here is that `elpy-shell-send-current-statement` sends the actual current statement, without indentation. So this sends: `if True:` and then `print('elpy')` – which obviously breaks.

What is the expected behavior here? I do not know what people use this feature for. Do they expect this particular case to actually work – or rather, if they `C-RET` through the following, do they expect nothing to be printed?

```Python
if False:
    print('elpy')
```

Or do they expect this to be printed anyhow? This is not a stepping debugger after all.

I originally thought `C-RET` can be used to quickly run some code within a class, like run the `foo = ...` line:

```Python
class Foo(object):
    def bar(self):
        foo = frobnicate(23)
```

Should `C-RET` maybe detect if the following statements are indented more? That's tricky to discover.

So, I guess I find it difficult to think about what the right fix for this would be without understanding what the use case is. What do people use `C-RET` for? :-)

**Comment by ChillarAnand** [comment]
Ideal behavior: elpy should send statement without indentation. If it comes across `if foo:` kind of statements, it should send following statements with respective indentation. 

So
```python
if False:
    print('elpy')
```
shouldn't print any thing.

But this is not possible(?) to implement this when user is trying to execute statments alternatively from two different blocks.
```python
if True:
    x = 10
    print(x)

if True:
    x = 20
    print(x)
```

I think sticking with current behavior is ok.
May be we can skip sending `if True:` kind of statements as there is no point in sending them? 
```python
if False:
    print('elpy')
```
So this should print elpy.

Add this to documentation: Select block and send them to shell when dealing with indented region.

**Comment by jorgenschaefer** [comment]
Skipping `if` in general sounds weird to me. Not sure.

Documenting `C-return` and mentioning this would be nice, though.

**Comment by ChillarAnand** [comment]
> Skipping if in general sounds weird to me. Not sure.

Not only `if`, may be any statement that ends with ':' ?

**Comment by jorgenschaefer** [comment]
It would seem to me that it would be rather confusing if some statements are not sent at all, would it not?

**Comment by ChillarAnand** [comment]
Makes sense.
