### ISSUE TITLE
as you type syntax checking

### ISSUE THREAD

**Issue by zacchiro** [jorgenschaefer/elpy#676]
As far as I can tell Elpy only checks syntax when a file is saved (the doc is consistent with that, saying: *Whenever you save a file, Elpy will run a syntax check and highlight possible errors or warnings inline*).

It'd be lovely to have a way to configure Elpy so that syntax checking is done on the fly, while you type.
That's because if you don't save often, it might happen that you've introduced pep8 issues in a place that is not visible when you save, resulting in overlooked issue unless you also do C-c C-v.

(As a background, before switching to Elpy I used to have a much simpler Emacs/Python configuration, which was not up to par with what Elpy does, but which was better in the above respect. Here's what I was using:

    (add-hook 'python-mode-hook 'flymake-mode)
    (add-hook 'python-mode-hook 'flymake-python-pyflakes-load)
    (setq flymake-python-pyflakes-executable "flake8")

having back support for something like the above with Elpy would be great.)

Thanks for Elpy!

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report :-)

On-the-fly checking of syntax problems has caused lots of problems for me, because Python files tend not to have correct syntax most of the time while editing for me, so I tended to have the current line highlighted a lot. Hence why Elpy disables this behavior.

You can simply remove `elpy-module-flymake` from `elpy-modules`. Elpy will then not configure flymake at all, and you can configure as you like.

Alternatively, you can add a function to `elpy-mode-hook` to change `flymake-start-syntax-check-on-newline` and `flymake-no-changes-timeout` to your liking, which are the two settings Elpy changes from the default.

Let me know if this solves your problem! :-)

**Comment by zacchiro** [comment]
On Thu, Oct 01, 2015 at 01:18:16AM -0700, Jorgen Schäfer wrote:
> Hello, and thanks for the report :-)

Thank you for your quick feedback :-)

> You can simply remove `elpy-module-flymake` from `elpy-modules`. Elpy
> will then not configure flymake at all, and you can configure as you
> like.

I'll try this, and let know here how it goes. OTOH,

> Alternatively, you can add a function to `elpy-mode-hook` to change
> `flymake-start-syntax-check-on-newline` and
> `flymake-no-changes-timeout` to your liking, which are the two
> settings Elpy changes from the default.

this doesn't work, and this is part of why I'm puzzled. What I see is
that flymake-start-syntax-check-on-newline is already set to true, and
flymake-no-changes-timeout is set to 0.5 --- I haven't changed those
values, so I suspect they're Elpy's defaults.  But the point is, they
don't seem to work: flymake is certainly not being invoked when newlines
are added/removed, nor after 0.5 seconds since the last change.

Is that the expected behavior or not?

(the interaction between Elpy and Flymake are not entirely clear to me
after reading the doc)

Cheers.
-- 
Stefano Zacchiroli  . . . . . . .  zack@upsilon.cc . . . . o . . . o . o
Maître de conférences . . . . . http://upsilon.cc/zack . . . o . . . o o
Former Debian Project Leader . . . . . @zacchiro . . . . o o o . . . o .
« the first rule of tautology club is the first rule of tautology club »

**Comment by jorgenschaefer** [comment]
> (the interaction between Elpy and Flymake are not entirely clear to me
after reading the doc)

Did you check those values in a Python buffer? Elpy sets those values buffer-local in Python buffers, not globally.

**Comment by zacchiro** [comment]
> Did you check those values in a Python buffer? Elpy sets those values buffer-local in Python buffers, not globally.

Ah, yes!, that was it. I've fixed my problem with this:

    (add-hook 'elpy-mode-hook
              '(lambda ()
                 (progn
                   (setq-local flymake-start-syntax-check-on-newline t)
                   (setq-local flymake-no-changes-timeout 0.5))))

Thanks a lot for your support.

**Comment by jorgenschaefer** [comment]
You're welcome, and enjoy Elpy! :-)

**Comment by lexleogryfon** [comment]
I actually encountered same problem now, but 3 years gone since issue was raised.
I just installed elpy, made venv, elpy-config, and issue was there - flymake did not checked syntax every 0.5 sec. by default it took a minute to refresh\redraw syntax highlights. even when elpy config stated that lymake-no-changes-timeout equal 0.5


Adding those strings from last zacchiro post solved my case. But it took me a long to find this solution and this was not easy\obvious.
@jorgenschaefer don't you think this is an bug, and it should be solved by elpy package, since elpy explicitly declares it as configurable option? but changing the value of this option does not make any affect, but it should as promoted.

Since user open *.py files in elpy mode , and all other features of elpy-mode and flymake seem to work out of the box (like autocompleteion, syntax check during initial file opening, and so on), without the special requirement to manually edit ~/.emacs , so mortal guess flymake-no-changes-timeout from elpy-config menu, should too, if it has been set there.


=======
sincerely thanks for beautiful elpy package

**Comment by jorgenschaefer** [comment]
I'm afraid I do not know what is happening there. Does it also happen if you do not have any personal configuration?

**Comment by lexleogryfon** [comment]
without ~/.emacs file , my emacs doesn't load elpa and can't activate virtual env. 

https://gist.github.com/lexleogryfon/d0da72f9505772849573063d14802d4f

**Comment by jorgenschaefer** [comment]
You can start Emacs with `emacs -Q`, then run `M-x package-initialize` and `M-x elpy-enable` to test.

**Comment by lexleogryfon** [comment]
Tried your recommendation, issue still exist. flymake refreshes syntax highlight only after ~1 minute. I start `emacs -Q -nw` because my main goal\use-case is to use it as CLI editor. But issue still exist and could be reproduced with GUI `emacs -Q', in my environment.

**Comment by jorgenschaefer** [comment]
I am afraid I have no idea what might be causing this.
