### ISSUE TITLE
el-get installer and elpy

### ISSUE THREAD

**Issue by romankrv** [jorgenschaefer/elpy#691]
Why haven't an alternative install of elpy via el-get installer?  
How get it?
Thanks

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the question!

I am afraid I do not use el-get, and I have no idea how to support it. The official way to get Elpy is by using the official package manager of Emacs, `package-install`. See the README for details. If you want to add Elpy to el-get, whatever that means, feel free! :-)

Does that answer your question?

**Comment by oxyum** [comment]
@romankrv 

    M-x  el-get-install<RET>elpy

works fine for me. Do you have any problems with it?

**Comment by romankrv** [comment]
oxyum: Do you have your emacs config in the public? 
Of course, i try make it as you've advised me, but it shows me the errors

--
Warning (emacs): Unable to activate package `elpy'.
Required package `company-0.8.2' is unavailable
Warning (emacs): Unable to activate package `elpy'.
Required package `company-0.8.2' is unavailable
Warning (initialization): An error occurred while loading `/Users/admin/.emacs.d/init.el':

Symbol's function definition is void: elpy-enable

I glad to see your emacs conf

Thanks

**Comment by oxyum** [comment]
@romankrv No, I have no my config in public, and my config is to complicated to find elpy-related parts only. :(

Just now I tried install elpy into clean emacs installation and it works fine, so it's not uniq to my configuration.

Your errors looks pretty weird, because company-0.8.2 is more than year old now. el-get uses company-mode and elpy from git, so it should use latest versions.

So I suggest you following actions:
    M-x el-get-self-updaty<RET>
    M-x el-get-update-all<RET>yes<RET>

    M-x  el-get-reinstall<RET>company-mode
    M-x  el-get-reinstall<RET>elpy

If this doesn't help, try to find new emacs version. I'm using Ubuntu (12.04 and 14.04) with latest emacs snapshots. So I doesn't know how it works with older versions of emacs.

**Comment by oxyum** [comment]
@romankrv Any updates?

**Comment by jorgenschaefer** [comment]
Lacking further updates, I assume the problem is resolved. Please do not hesitate to open a new issue if you have further problems, and enjoy Elpy.

@oxyum, thank you very much for jumping in and helping. It is greatly appreciated. :-)
