### ISSUE TITLE
C-c C-d not working consistently

### ISSUE THREAD

**Issue by jkitchin** [jorgenschaefer/elpy#695]
I have this in a Python buffer:

    from scipy.integrate import odeint
    from pycse import  nlinfit

if I have point on odeint, I see a message with the function signature, and I can type C-c C-d to get the documentation. That does not work with point on nlinfit, even though I can run "pydoc pycse.nlinfit" at the command line. Any idea why? Thanks!

**Comment by jorgenschaefer** [comment]
Hello! This can be for a number of reasons. To understand that, it's good to know how Elpy tries to find the docstring in these circumstances. It tries two things in turn:

- First, it asks the current backend (Jedi or Rope) if they have any idea. These backends can do elaborate syntax analysis, and can find docstrings through renaming of variables and such. On the other hand, due to the complex ways Python works with imports, C modules, etc., they might not figure things out from the source.
- When that does not result in anything, Elpy asks pydoc for the symbol at point. In this case, that's `nflinfit`, which is obviously not what Pydoc can work with. Elpy does not do syntax analysis here, it just passes the symbol at point to pydoc. So this won't find things.

It seems your current backend is not picking up nlinfit correctly here. If you think it should, it might be an idea to file a feature request with the backend's author. If you post the output of `M-x elpy-config`, I'll see if I can make a reproduction case for you to figure out what's going on here. :-)

**Comment by jkitchin** [comment]
The pycse package is located here: https://pypi.python.org/pypi/pycse/
and installable with pip. There could be some import magic getting in the way since the functions (e.g. nlinfit) get imported in __init__.py from another file in the module.

Thanks for elpy by the way, it is pretty great!

here is my elpy config

Elpy Configuration

Virtualenv........: User (/Users/jkitchin/Library/Enthought/Canopy_64bit/User)
RPC Python........: 2.7.6 (/Users/jkitchin/Library/Enthought/Canopy_64bit/User/bin/python)
Interactive Python: python (/Users/jkitchin/Library/Enthought/Canopy_64bit/User/bin/python)
Emacs.............: 25.0.50.1
Elpy..............: 1.9.0
Jedi..............: 0.9.0
Rope..............: 0.10.2
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: flake8 (/Users/jkitchin/Library/Enthought/Canopy_64bit/User/bin/flake8)

The directory ~/.local/bin/ is not in your PATH, even though you do not have an
active virtualenv. Installing Python packages locally will create executables in
that directory, so Emacs won't find them. If you are missing some commands, do
add this directory to your PATH.

**Comment by jorgenschaefer** [comment]
Ah, pycse uses numpy – the whole numpy and scipy toolkit uses a lot of deep voodoo for efficiency (e.g. modules written in C, which have difficulties with introspection), so I am not surprised Jedi and Rope have problems finding those.

If you have not done so already, you can try Jedi instead of rope with your setup: `M-: (setq elpy-rpc-backend "jedi")` and `M-x elpy-rpc-restart` to see if that helps. Sometimes, Jedi can find more information than Rope (and sometimes the other way around).

Other than that, I'm afraid this is a feature request for either Jedi or Rope, and not something Elpy can do much about :-/

Thanks for the kind words, though. I hope that you enjoy Elpy despite this problem!

**Comment by jkitchin** [comment]
Thanks for the tip. jedi does a little better with pycse indeed!

Jorgen Schäfer writes:

> Ah, pycse uses numpy – the whole numpy and scipy toolkit uses a lot of deep voodoo for efficiency (e.g. modules written in C, which have difficulties with introspection), so I am not surprised Jedi and Rope have problems finding those.
>
> If you have not done so already, you can try Jedi instead of rope with your setup: `M-: (setq elpy-rpc-backend "jedi")` and `M-x elpy-rpc-restart` to see if that helps. Sometimes, Jedi can find more information than Rope (and sometimes the other way around).
>
> Other than that, I'm afraid this is a feature request for either Jedi or Rope, and not something Elpy can do much about :-/
>
> Thanks for the kind words, though. I hope that you enjoy Elpy despite this problem!
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jorgenschaefer/elpy/issues/695#issuecomment-150518078

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by jorgenschaefer** [comment]
Glad to hear this! Enjoy Elpy! :-)
