### ISSUE TITLE
Switch MELPA back to the master branch

### ISSUE THREAD

**Issue by kootenpv** [jorgenschaefer/elpy#748]
When is this updated? I see yapf is included in the source here, but MELPA is not the same.

If I want to run the latest version, will I have to clone myself?

**Comment by ChillarAnand** [comment]
Last elpy relase was on 1st of nov. So that is when melpa is updated.  Only stable releases will be updated on melpa.

If you need latest version, you have install it manually.

```
rm -rf ~/.emacs.d/elpa/elpy*
mkdir ~/Projects
cd ~/Projects
git clone https://github.com/jorgenschaefer/elpy
```
Add the following to your ~/.emacs.d/init.el or ~/.emacs:
```
(add-to-list 'load-path "~/Projects/elpy")
(load "elpy" nil t)
(elpy-enable)
```

**Comment by kootenpv** [comment]
This might want to be considered; maybe on MELPA stable do it like that, but people might want to just have the latest and greatest from MELPA (the default one).

**Comment by ChillarAnand** [comment]
There  has been a long discussion about this https://github.com/milkypostman/melpa/pull/1129

**Comment by kootenpv** [comment]
@ChillarAnand Ouch, quite a long and painful discussion. It does explain a few things. It's unfortunate there is not a better solution. Perhaps it would be possible to offer 2 versions of `elpy` on MELPA?

**Comment by ChillarAnand** [comment]
> Perhaps it would be possible to offer 2 versions of elpy on MELPA?

You mean two different packages?

**Comment by kootenpv** [comment]
Yea, indeed. `elpy-dev` and `elpy-stable`. Since MELPAs default is using "most recent", and MELPA stable is not the default, but elpy wants it differently, one option might be to maintain 2 versions of elpy instead.

**Comment by ChillarAnand** [comment]
I don't think it is a good idea to have same package with two different names in same repository.

**Comment by kootenpv** [comment]
Well, it is also not possible to use the latest version from `elpy` from MELPA now? It's actually elpy that is different from MELPA (with reasons stated in the thread), but that means there is currently no solution for people who want bleeding edge elpy.

**Comment by ChillarAnand** [comment]
You can install it as mentioned  [in above comment](https://github.com/jorgenschaefer/elpy/issues/748#issuecomment-167493592).

**Comment by kootenpv** [comment]
@ChillarAnand My point is that [the above comment](https://github.com/jorgenschaefer/elpy/issues/748#issuecomment-167493592) is not an integrated solution.

I'd have to manually run `git pull`.

**Comment by ChillarAnand** [comment]
That is the best I know. May be @jorgenschaefer can you help you with this.

Here is a simple solution. You can pull master before loading elpy

```
;; in you init.el
(shell-command "cd /path/to/elpy; git pull origin master")
;; load elpy
```

**Comment by jorgenschaefer** [comment]
Hello! Sorry for the late response, I was on vacation. As @ChillarAnand explains, there has been quite a history here. While you expect MELPA to contain the latest versions, a number of other uses in the past were bitten by that. I am afraid that I'd rather make life easier for non-advanced users.

On the other hand, both MELPA and Elpy have changed a lot since that discussion. It is nowadays much more widely known that MELPA packages tend to break, and people can use MELPA stable (which did not exist back then) if they prefer stability. Also, Elpy has matured a lot, too, so that the current development version is a lot less likely to break for the average user.

I'm considering switching MELPA back to the master branch. I'm open for comments on this, though.

**Comment by gopar** [comment]
Isn't master on Melpa already? If so,can close this

**Comment by jorgenschaefer** [comment]
Yeah, that happened a while ago, I just forgot to close this ticket. Thanks!
