### ISSUE TITLE
company module is too intrusive

### ISSUE THREAD

**Issue by vspinu** [jorgenschaefer/elpy#788]
I think company module is way too intrusive. I have opened an [issue in company](https://github.com/company-mode/company-mode/issues/463) but I guess it's more of an elpy problem. 

Company mode is so ubiquitous that you would expect most users would have their own configuration by now. So sneakly [setting](https://github.com/jorgenschaefer/elpy/blob/master/elpy.el#L3169-L3179)  keys in company map (C-d), messing with dabbrev and setting idle company delay behind the user's back doesn't seem right. Most of the users would have already customized these features themselves.

I think the readme should mentioned `elpy-modules`` and what they overwrite in the backgraound. 

There could even be two versions of `elpy-modules` overwrites - one lightweight and non-contentious which would simply initialize the functionality with most basic defaults, and another one - feature reach and intrusive, like it is right now.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for raising this issue!

Elpy is meant as a mode you can install on a plain Emacs and have it be useful. A lot of the things in Elpy could, arguably, be left out because experienced Emacs users surely can (or already have) configured them themselves.

Elpy goes the other way. We provide a default config that works for people with nothing else installed, and allow experienced users like you to tell it to not configure things you already do yourself. I find it a lot more sensible to expect experienced users to put in some configuration effort than new users.

I'm fine if you want to add some documentation on the wiki that mentions the modules and what they do, of course. Maybe a new page "Elpy for experienced users"? The README is a bit too crowded already for this kind of information, though.

I hope this answers your concerns?

**Comment by vspinu** [comment]
> Elpy goes the other way. We provide a default config that works for people with nothing else installed,

Thanks for this. It's very helpful indeed. The question is, do you want to help new emacs users or  new python users? I think most of elpy "new" users will be of the second  type. 

I guess my main problem is that I cannot easily isolate things what I want to keep. Everything seems to be too tightly coupled. For example, I want to keep company module because of semantic/capf cleanup. But I don't want it to interfere with my keys.  

Elpy rebinds C-d not only in python mode but everywere else. A lot of modes have full doc maps on C-d. Given that company is very often active that completely messes things up.  

> I find it a lot more sensible to expect experienced users to put in some configuration effort than new users.

This is not that it easy as it sound. How do I actually do that? Instalation instructions say very little about that.

Elpy config is non-standard. You configure both globally and locally. So for each thing that you change I have to go and figure how and where to unset it. Which ones go in elpy hook, which ones in (after-load "elpy"), which ones by disabling the entry in `elpy-modules`. 

I think there are two separate things - elpy-core as a completion bakend and a set of utilities, and elpy-configuration which provides user friendly defaults for elpy and other modes. Currently, these two are badly intermingled. 

Why not provide `elpy-config.el`, like other modes do, which would contain the _recommended_ configuration. Then new and experience users alike can go through the file and keep the full file or only things that they need.

> We provide a default config that works for people with nothing else installed,

Then this should be clearly stated in the instalation instruction. I discovered this the hard wa

**Comment by jorgenschaefer** [comment]
> I guess my main problem is that I cannot easily isolate things what I want to keep.

Sadly, Emacs makes it very difficult to isolate these things in a useful way. As an experienced Emacs user, you can look at the module definition and copy the parts you don't like, though. (That seems to be the standard way in Emacs, come to think of it.)

> This is not that it easy as it sound. How do I actually do that? Instalation instructions say very little about that.

Same ways as in any other Emacs mode, really. You start with `M-x customize` (Elpy provides a quick interface to that in `M-x elpy-config`, but you don't have to use it), follow up with `M-x apropos-variable RET elpy RET` and read variable documentation, and if all else fails, you look at the source code.

> Why not provide `elpy-config.el`, like other modes do, which would contain the recommended configuration.

Interesting idea. That would mean moving about 60% of `elpy.el` to `elpy-config.el`, and I'm not sure if that makes things easier. I'll think about it, though, thanks for the suggestion!

**Comment by vspinu** [comment]
> Same ways as in any other Emacs mode, really. You start with M-x customize 

This doesn't work. You rebind a lot of stuff either globally or on buffer setup.

My point was that you configure stuff programaticaly without having custom variables for your configurations. A user like me has no choice but to unset things in `elpy-mode-hook` or alternatively, deactivate some modules and copy paste the interesting code from the elpy source. 

One easy workaround might be to have increasing by intrusivness levels of configuration. On level 0 you set up the basics, on level 10 you setup most subjective stuff (everything an end user might ever need).  Then, I as a user, pick a level which is most compatible with my existing .emacs configuration.

> Interesting idea. That would mean moving about 60% of elpy.el to elpy-config.el, and I'm not sure if that makes things easier. I'll think about it, though, thanks for the suggest

I meant only the external-to-elpy config; those settings that concern managing other packages and might interfere with their settings - the modele-management part as controled by `elpy-modules`.

More generally, elpy is the only emacs IDE that keeps all its stuff in one file. It has many isolated pieces in there (company, eldoc, rpc, external-packages-config etc.) which deserve their own file IMO.  At the least that would make the code more readable and the system more easy to reason about.

**Comment by jorgenschaefer** [comment]
> My point was that you configure stuff programaticaly without having custom variables for your configurations. A user like me has no choice but to unset things in elpy-mode-hook or alternatively, deactivate some modules and copy paste the interesting code from the elpy source.

I am confused. Customizing `elpy-modules` is the right way to disable customizations made by Elpy.

You are complaining about that this is not fine-grained enough. To which I said that it's difficult to know the correct level of detail at which to provide these customizations. I'm afraid I'm not willing to make the customization more fine-grained than it is right now. You have all the tools to disable Elpy's customizations.

Aside from making these options more fine-grained, is there anything else I can help you with?

**Comment by vspinu** [comment]
> I'm afraid I'm not willing to make the customization more fine-grained than it is right now.

Refining customization is a workaround. It will not solve the problem.

My proposal is to split the package into the core elpy functionality and elpy "benevolent" configuration of external packages. Call it elpy-config.el or something like that which people can require separately or copy paste configuration from there.

Could you consider at least removing the most obvious "wrongdoings" like setting up keys in foreign keymaps?

> Aside from making these options more fine-grained, is there anything else I can help you with?

Original bug report on company site is a bug. You are deactivating file completion in strings. Either elpy or company has to deal with it.

**Comment by jorgenschaefer** [comment]
> My proposal is to split the package into the core elpy functionality and elpy "benevolent" configuration of external packages. 

This can be one of two things. Either, this would mean splitting most of Elpy out of Elpy, because most of Elpy is about configuring external packages. Or it would be about moving `elpy-modules` and associated functionality into a separate file. I do not see the benefit in that, you can easily do `(setq elpy-modules nil)` if you do not like these settings. You can also easily look at the source code of each module to see exactly what it does.

I do not see how this proposal would improve Elpy, so I'm afraid I'm not interested in doing this.

> Could you consider at least removing the most obvious "wrongdoings" like setting up keys in foreign keymaps?

I do not consider these to be "wrongdoings". Elpy provides a sensible default configuration which you can disable if you like. I considered this and decline.

**Comment by vspinu** [comment]
Ok then I guess me and other new users will have to suck it up. 

Could you please add a warning in the readme and installation instruction about what those elpy modules are doing under the hood? And make it bold face? It would save some users hours of frustration of digging up what is going on. It took me a good hour or more to crack up the company related bug.

Besides this esoteric configuration bit, it's a trully great package. Thanks!

**Comment by jorgenschaefer** [comment]
I am sorry Elpy caused you hours of frustration in trying to figure out what is going on.

I still do not know what kind of warning you have in mind. The problem here is not that Elpy does something it should not which it can reasonable warn about. The problem is that you have done extensive customization to your Emacs that happen to conflict with what Elpy is doing. That's just an unfortunate side effect of how Emacs works and there is nothing Elpy can do about it without being a worse tool for other people, especially those with less experience than you have.

The warning that would work is "if you do extensive configuration of Emacs, Elpy might conflict with some of what you do, check the source code to see all Elpy does". That's a non-warning.

I am happy to hear you still like Elpy, though, and I hope I can help you more with other issues you might have.

**Comment by vspinu** [comment]
> The problem here is not that Elpy does something it should not which it can reasonable warn about.

I disagree. No package should mess up with other packages' defaults unless it is specifically designed to do so - a config package. Elpy does a bit of both, it provides a lot of unique functionality and is a config package.

> The problem is that you have done extensive customization to your Emacs that happen to conflict with what Elpy is doing.

I am afraid this is not correct. It has nothing to do with my configuration. I haven't configured `company-dabbrev-code-everywhere`. Elpy overwrites the default value of `nil` and screwes the company-file completion. I didn't bind C-d; it's  the default emacs `org-delete-char` on it. You are overwriting that in company-active-map which means that I cannot delete characters when company is active.

Another controversial setting - you are reseting `company-idle-delay` to 0. That ruins the environment on slow machines and especially on remotes. Dgutov set it to .5 by default for a reason.  Even if it seems to work for Elpy backend, it might not work for other user's backends.

> The warning that would work is "if you do extensive configuration of Emacs, Elpy might conflict with some of what you do, check the source code to see all Elpy does".
> That's a non-warning.

I am probably extremely bad at conveing the idea. You are overwriting other author's and user's settings. *You need to warn about that!* It's not stated anywhere that Elpy is a non-standard config package. 

The following warning would work:

_Warning: In addition to its core functionality Elpy is also a configuration package. For a range of external packages  (company-mode, flymake, pyenv, yasnippet etc) `Elpy` sets some variables to non-default values. This might result in conflicts and unexpected behavior for some users. For more details see the custom  variable `elpy-modules` and look through the initialization of the module in the Elpy source code._

**Comment by jorgenschaefer** [comment]
> No package should mess up with other packages' defaults unless it is specifically designed to do so - a config package.

So you want Elpy to also not change `company-backends` to add its own backend, because that would change another package's defaults? I still disagree.

> I am probably extremely bad at conveing the idea.

No, I think we simply disagree on a very fundamental level.

For me, Elpy is a package that configures Emacs to be a Python development environment.

For you, it's a package that provides some functionality you might or might not want to add to your editor.

That is fine. Emacs has traditionally been all about not having any default settings just in case a user prefers something else. I disagree strongly with that philosophy, and so all my packages provide sane defaults from the start.

When I wrote Elpy, the suggested way of writing Python in Emacs included copying and pasting a large number of configuration settings from other people around and adjusting them slightly to your needs. The _whole point_ of Elpy has always been to turn Emacs into a Python development environment, without the need to do that. This includes configuring other packages.

This is also why we seem to be talking past each other so much here: You want Elpy to be something I most definitely and absolutely do not want it to be (and vice versa).

I'm happy to hear specific arguments against individual configuration choices in Elpy, but you will not get me to change Elpy to stop configuring other packages as the default thing it does.

**Comment by vspinu** [comment]
> You want Elpy to be something I most definitely and absolutely do not want it to be (and vice versa).

Actually I am fine with Elpy configuring other packages as long as this is stated clearly as an intent of the package. Sorry if I didn't make that clear. It's all about being explicit vs sneaky, and being standard vs config package. 

I have used pretty much every other IDE in Emacs (SLIME, CEDET, Cider, Geiser, Eclim and ESS which I develop). None of them messes with other packages. So, I just didn't expect Elpy to be different in that respect.

>  I disagree strongly with that philosophy, and so all my packages provide sane defaults from the start.

I hope you don't mean sane defaults for other packages;) Would you be happy if some other package author were claiming to provide sane defaults for your package?

**Comment by jorgenschaefer** [comment]
> I hope you don't mean sane defaults for other packages;)

I do.

> Would you be happy if some other package author were claiming to provide sane defaults for your package?

If they don't like mine, sure?

**Comment by jorgenschaefer** [comment]
A quick check in ess-mode.el tells me that `ess-mode` at least changes the default values of `mode-line-process`, `completion-at-point-functions`. I think we both want our modes to change other packages' defaults, we just disagree which variables are "ok" to change and which are not.

**Comment by vspinu** [comment]
On 30 January 2016 at 20:59, Jorgen Schäfer <notifications@github.com>
wrote:

> A quick check in ess-mode.el tells me that ess-mode at least changes the
> default values of mode-line-process, completion-at-point-functions.
>

Let's not get this into the ridiculous zone.  Those are not user custom
variables.

You surely got my point.  In your place I  would defenitely split all those
configs into separate file(s) and abandon  that `elpy-module` abomination.
An optional `(require 'elpy-config)` would simplify everyone's life.  You
can then have multiple configuration files and even user contributed
elpy-config files. It's an uniformly better approach than the current one.

**Comment by jorgenschaefer** [comment]
> would simplify everyone's life.

Among all your rudeness, you confused "everyone" with "your". If you wish to have a discussion with me, please try to behave like a decent person. You are currently not.

I think the topic is well and thoroughly discussed now. If you have other issues with Elpy that do not revolve around how you think I should develop my software, please do not hesitate to open a new issue.

**Comment by dgutov** [comment]
@jorgenschaefer Regarding `company-idle-delay`, you'd be better off setting it to something like 0.01, if the higher values are not to your liking.

**Comment by vspinu** [comment]
> Among all your rudeness, you confused "everyone" with "your". If you wish to have a discussion with me, please try to behave like a decent person. 

Hm. I am sorry if I appeared rude. Your comment just came as a surprise to me. I cannot justify those. It's a language thing I guess. After hours of pointless discussion about adding one line to README you got me. So I told you directly that IMO your approach is plain wrong. It's my opinion.  Not a big deal. Sorry to hurt your feelings; wasn't intentional. 

I really do think you are a great developer. You just seem to be thinking that other package authors are idiots who cannot decide for their own defaults and you need to correct them.

It's your software, you decide what to do. Fair enough. My task was to tell you about my frustrating experience with your package and propose solutions in order to improve it.  Feel free to ignore it of course.

**Comment by jorgenschaefer** [comment]
> @jorgenschaefer Regarding `company-idle-delay`, you'd be better off setting it to something like 0.01, if the higher values are not to your liking.

Thank you, will do!
