### ISSUE TITLE
Code completion not working for newly installed module

### ISSUE THREAD

**Issue by jackterranova** [jorgenschaefer/elpy#829]
I highly doubt this is an issue with elpy.  But a newly installed Python module will not auto complete.  All other imports seem to be auto completing fine.  Maybe it is how I installed the module.  

The module is cx_Oracle for database access.

How might I troubleshoot?

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the question! The name of the module name sounds like it's written in C, that usually makes introspection a lot more tricky. If `M-x elpy-config` does not show anything out of the ordinary, you can try using Jedi instead of Rope (or the other way around) and hope that works. But it might very well be that you're out of luck and the C module does not sensibly export its API. :-(

**Comment by jackterranova** [comment]
Yes.  I tried both rope and jedi with no luck.  

Good to know that this is an issue specific to the module.  

Thanks
