### ISSUE TITLE
who can tell me how to create first python project using elpy?

### ISSUE THREAD

**Issue by jacobishao** [jorgenschaefer/elpy#846]
who can tell me how to create first python project using elpy?

**Comment by jorgenschaefer** [comment]
Hello. I guess you found an answer to your question? I hope you could create a good new project, and enjoy Elpy! :-)

**Comment by jacobishao** [comment]
yeah ,if i need to make two python source files belong to one project ,i
need to you emacs command to set it; is it right?

2016-03-28 20:25 GMT+08:00 Jorgen Schäfer <notifications@github.com>:

**Comment by jorgenschaefer** [comment]
Depends on what kind of "project" you mean, or what you want to do with that.

Elpy will try to auto-discover a project based on a few special files, among them  the root of your current git repo or the existence of a `setup.py` file (see `elpy-project-root-finder-functions`). Otherwise, it will use the directory of the current file.

Does that help?

**Comment by jacobishao** [comment]
oh ! wonderful !
i got it.
thank you very much!!!!

2016-04-08 15:49 GMT+08:00 Jorgen Schäfer <notifications@github.com>:

**Comment by jacobishao** [comment]
[image: 内嵌图片 1]
every time I want to save the file , it will ask me  that.
Is there any way to skip the alert?

2016-04-12 15:32 GMT+08:00 Jacobi Shao <shaojacobi@gmail.com>:

**Comment by jorgenschaefer** [comment]
> every time I want to save the file , it will ask me  that.

Ask you what, exactly?
