### ISSUE TITLE
default value for elpy-test-django-runner-command

### ISSUE THREAD

**Issue by gaetano-guerriero** [jorgenschaefer/elpy#904]
Any reason why default value ``elpy-test-django-runner-command`` is not something like
``./manage.py test --noinput``

With the default ``django-admin.py test --input`` I must manually:
* set ``DJANGO_SETTINGS_MODULE``
* set ``PYTHONPATH`` to include current project root

**Comment by jorgenschaefer** [comment]
> Any reason why default value `elpy-test-django-runner-command` is not something like
`./manage.py test --noinput`

Yes. It's not easy to locate the `manage.py` script automatically, and that script does not necessarily exist (some people remove it because it's basically clutter). Hence simply using `django-admin.py` is a better default. Setting `DJANGO_SETTINGS_MODULE` correctly in the virtualenv is good practice anyhow, as it allows other scripts to run easily, too. But this is just a sensible default – you can easily set `elpy-test-django-runner-command' yourself, though, if you prefer other approaches. :-)

Does this answer your question?

**Comment by gaetano-guerriero** [comment]
My thought was that a ``manage.py`` in the django project root was more or less a standard, and in the last django versions the script also has the executable bits set. So maybe using ``manage.py`` we could have a "just works"  behavior with zero configuration in the majority of cases.
Anyway if it's not general enough as I thought of course I have no problem in customizing ``elpy-test-django-runner-command`` !

Thank you for your quick response and your great work on this package.

**Comment by jorgenschaefer** [comment]
"Sensible defaults" are always tricky – someone is bound to have a setup that does not fit them :-( Thank you for the suggestion, though, and enjoy Elpy!
