### ISSUE TITLE
Running unit test with bad project root (Django)

### ISSUE THREAD

**Issue by vindarel** [jorgenschaefer/elpy#931]
Hi !

So today I finally discovered this elpy feature.

First I had to dive in the code to see and edit the following variable `(setq elpy-test-django-runner-command '("./manage.py" "test"))`.

Then I tried to run my unit test with `M-x elpy-test-django-runner` but it failed because the project root was one directory too up.

I edited elpy.el's `elpy-test-at-point` like so

```
    ;; (let* ((top (elpy-library-root))
  (let* ((top (elpy-project-find-projectile-root))
```

and it worked :)

So I don't know if it's just me, but to me this elpy command is broken. Is that so, or can I fix the project root by another mean ?

Using elpy 20160613.

thanks !

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! Your problem here is that you are using `manage.py` to run the tests, and then even use a relative path to run it. That means that the way Elpy finds project roots breaks. Your first "fix" there, changing `elpy-test-django-runner-command`, is likely the wrong way to solve the actual problem you have.

Elpy uses `django-admin.py` instead of `manage.py` for this very reason: The location of `manage.py` is not uniform and easy to find. Instead of doing those changes you did there, you should just set the `DJANGO_SETTINGS_MODULE` environment variable to your settings module, and everything should work out of the box.

Does this help?

**Comment by vindarel** [comment]
mmh, it helps to know that we must change this environment variable, but all isn't that clear to me.

> That means that the way Elpy finds project roots breaks

what's the relation ? Projectile finds the project root and Elpy runs a correct command, relative pathname or not.

I understand now the use of django-admin.py with the environment variable, but it just looks more complicated to me. We must set the variable and change it for every project right ? Not with the way I did.

Actually I couldn't run my test with your method even on the terminal, I have an "Import by filename is not supported" error…

Regards

**Comment by jorgenschaefer** [comment]
> Projectile finds the project root and Elpy runs a correct command, relative pathname or not.

You assume that all projects have a `manage.py` at the project root. That's actually not all that common. Great that it works for you.

You also assume that test runners should be run from the project root, and not the library root. That's also not always the right thing.

I am not saying that "your way" is wrong or anything, I am just pointing out that just because it works for you does not mean that it works for everyone. :-)

> Actually I couldn't run my test with your method even on the terminal, I have an "Import by filename is not supported" error…

Could you provide the full command being run and the full error? Thank you!

**Comment by vindarel** [comment]
> You assume that all projects have a manage.py at the project root. That's actually not all that common.

Oh ok !

**Comment by gopar** [comment]
I'm guessing this is resolved?

**Comment by vindarel** [comment]
Hey, a last question. Do we agree that the actual way is to manually change an environment variable, for each project, and that what I did doesn't require this step, but is not universal. So, would you accept elpy to be configurable to accept one method or the other ? (I'm asking but I reckon I maybe should get myself more familiar with elpy before.) 

Thanks anyway

**Comment by jorgenschaefer** [comment]
The best way in my opinion is to set up your virtualenvs to set the environment variables correctly for each virtualenv.

What you did _accidentally_ works for you, because you have a very specific project layout. I don't think it's possible to make Elpy easily configurable for all possible project layouts, so let's just stick with this. You can easily set `elpy-test-django-runner-command` to your manage.py if needed.

**Comment by vindarel** [comment]
> What you did accidentally works for you, because you have a very specific project layout.

I'm surprised by this. I feel like I do exactly what teaches [the django doc](https://docs.djangoproject.com/en/1.10/topics/testing/overview/#running-tests): I am in my venv, I run `./manage.py test`. My project layout is just the classic one.

> You can easily set elpy-test-django-runner-command to your manage.py if needed.

I tried, but unfortunately this is not enough, because `elpy-test-at-point` will always return the library root, when I need the project root.

I have a PR coming, hoping it will make things clearer.

**Comment by gopar** [comment]
Closing this since `elpy-django.el` allows you to set the full path to `manage.py`, so issues like this won't happen.
