### ISSUE TITLE
invalid pointer error

### ISSUE THREAD

**Issue by chendaniely** [jorgenschaefer/elpy#933]
I'm not sure if this error stems from the fact that I'm using the Anaconda distribution for python,
but I've been getting an invalid pointer error when I'm in my python files.

```
Elpy Configuration

Virtualenv........: None
RPC Python........: 3.5.1 (/home/dchen/anaconda3/bin/python)
Interactive Python: ipython (/home/dchen/anaconda3/bin/ipython)
Emacs.............: 24.5.1
Elpy..............: 1.12.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: 0.1.7
Autopep8..........: 1.2.4
Yapf..............: 0.9.0 (0.10.0 available)
Syntax checker....: flake8 (/home/dchen/anaconda3/bin/flake8)
```

pastebin of error: http://pastebin.com/RBK9mF23

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report!

This likely means that some module you have installed does not like being imported. It might be enough to deinstall importmagic, because that's rather invasive in trying to import anything and everything. (Of course that means importmagic features won't be available …)

The real fix would be to make all modules you have installed safe against imports, but I do not know how to find out which module it is that is causing these problems.

**Comment by chendaniely** [comment]
I'm trying to find the import that's causing the issue.  do you think `pip install -e .` would break this?

I'm working on a package that hasn't been published to pypi yet

**Comment by chendaniely** [comment]
thanks @jorgenschaefer I think the main problem is also I use the anaconda python distribution.
Luckily I'm also on arch linux, so I reinstalled all the elpy packages using the package manager.

So far I haven't seen this error pop up...

**Comment by jorgenschaefer** [comment]
That's good news! :-) I'll close this report, but please do not hesitate to open it again or make a new one if you have further problems!
