### ISSUE TITLE
Finding project root

### ISSUE THREAD

**Issue by svictor9** [jorgenschaefer/elpy#957]
Hi, and thanks for elpy!

I’m new both to elpy and to python.

I’m trying to get elpy to recognize my project root.

The layout is simple: the global project is in "~/bin/Vsono" and the .py files which I actually edit are in "~/bin/Vsono/Vsono".

I have a virtualenv setup for ~/bin/Vsono. I initialize it in with pyvenv-activate and the code works as expected. 
Then I check `elpy-project-root` and it is nil.
Next I use `elpy-set-project-root` to set it manually to either "/home/vic/bin/Vsono/" or to "/home/vic/bin/Vsono/Vsono/". In both cases, running `elpy-find-file` afterwards fails, with
`No project root found`. Actually the Messages buffer says it with an additional line:
```
No project was defined for the current file.
ffip-project-search: No project root found
```

I don’t understand why "no project was defined" since elpy-project-root is actually set (I checked it again with `C-h v` after running `elpy-set-project-root`).

elpy-library-root is "~/bin/Vsono/Vsono/"

Some background: I don’t use git for this project. I use projectile and placed a .projectile file in ~/bin/Vsono. I also tried placing one in ~/bin/Vsono/Vsono but it didn’t seem to change anything for elpy.

elpy-config says:
```
Virtualenv........: Vsono (/home/vic/.virtualenvs/Vsono)
RPC Python........: 2.7.12 (/home/vic/.virtualenvs/Vsono/bin/python)
Interactive Python: ipython (/usr/bin/ipython)
Emacs.............: 24.5.1
Elpy..............: 1.12.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: 0.1.7
Autopep8..........: 1.2.4
Yapf..............: Not found (0.11.1 available)
Syntax checker....: flake8 (/home/vic/.virtualenvs/Vsono/bin/flake8)
```

Could you please give me some guidelines on how it is supposed to work?

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! Elpy works with Projectile, so you should be able to use `M-x projectile-switch-project` and then things should work.

One possible source of confusion here is that Emacs has no concept of "project" as such. Elpy can only guess the project the current buffer might be in.

**Comment by svictor9** [comment]
Thanks! Well, projectile actually recognizes my project. All its functions work as expected. It’s just that in a buffer where I can `projectile-find-file`, I can’t `elpy-find-file`: it says "no project root found". Indeed `elpy-project-root` for that buffer is nil. If I set it with `elpy-set-project-root` for that buffer (and check that it is correctly set with C-h v) the result stays the same. I don’t know how to investigate this further. 

It’s not such a problem actually for `elpy-find-file` because I can use `projectile-find-file` instead. But I suspect that other things in elpy won’t work as expected if it doesn’t know about my overall project. For instance, I can only `elpy-goto-definition` from a function call if the function is defined in the same file. If the function is defined in another file of my project, elpy says "no definition found". I suppose it should find it if it knew about the overall project, isn’t it?

**Comment by fresheed** [comment]
Hello, guys! I've been discovering Elpy too and met same problem: I can't use elpy-find-file because of "No project root found" error. I tried manually setting it with elpy-set-project-root and also created .projectile file in desired directory.
The strange thing is that I can run tests without project root. There are (project dir)/src and (project dir)/tests, and it is possible to launch tests with C-c C-t from src/ files. But I can't import any module of src/ to tests/. I tried importing:
1. (project dir).src
2. src
3. just file name
but none of them is working (test runner throws error ending with  " _'module' object has no attribute '[test file name]'_ ")

**Comment by jorgenschaefer** [comment]
Hm. That error actually should never happen. Can you try M-x toggle-debug-on-error, reproduce this, and post the backtrace you get?

**Comment by JosefAtmin** [comment]
Hello!

The hint that Elpy uses Projectile was very helpful.  I had the same problem that Elpy did not find files, because project-root was not available even though I just set it. After installing Projectile, it does not complain about not finding files. It might be helpful to check for the presence of Projectile at the configuration of Elpy, like you do for many other packages.

However, it still does not work as I would expect. I have two files in my directory ~/Test

[Hello.py]
print "Hello"

[Main.py]
import Hello
print "Goodbye"

If I run 'python Main.py' from a command line, the output is

Hello
Good by

If I run Main.py from within that file using Elpy by pressing C-c C-c the output is only  

Good by

It does not complain not finding Hello.py, but it does not seem to execute it.

Is that how it should be? Is there something here I don't understand?  I am new to Python and Elpy.

Cheers, Josef.

**Comment by JosefAtmin** [comment]
Hello!

The hint that Elpy uses Projectile was very helpful. I had the same problem that Elpy did not find files, because project-root was not available even though I just set it.  After an hour of research on the Internet and installing Projectile, it does not complain anymore about not finding files. It might be helpful to check for the presence of Projectile at the configuration of Elpy and give warning, like you do for many other packages.

Cheers, Josef.

PS: Thanks for Elpy.  I just tried eclipse and pycharm, which are great programs, but I like about elpy that you can run selections and try out single commands in the python shell within emacs. These are features I did not find in the other programs.

**Comment by jorgenschaefer** [comment]
Glad to hear it works now, and that you like Elpy! Enjoy :-)
